import { contentLibraryStats } from "./content-library";

export type TopicId = "peppers" | "buildings" | "sharks" | "space" | "jets" | "mixed";
export type KnowledgeTopic = Exclude<TopicId, "mixed">;
export type Difficulty = 1 | 2 | 3;
export type HeatBand = "not spicy" | "mild" | "warm" | "hot" | "very hot" | "insane";

export type VisualFit = "cover" | "contain";

export type ImageFields = {
  image: string;
  imageSourceFile: string;
  imageSourceUrl: string;
  imageCredit: string;
  imageFit?: VisualFit;
  imagePosition?: string;
};

export type Pepper = {
  id: string;
  name: string;
  heat: HeatBand;
  shuMin: number;
  shuMax: number;
  color: string;
  image: string;
  imageSourceFile: string;
  imageSourceUrl: string;
  imageCredit: string;
  imageFit?: VisualFit;
  imagePosition?: string;
  fact: string;
};

type PepperSeed = Omit<Pepper, "heat">;

export type Building = {
  id: string;
  name: string;
  city: string;
  country: string;
  heightFt: number;
  floors?: number;
  status: "finished" | "under construction";
  image: string;
  imageSourceFile: string;
  imageSourceUrl: string;
  imageCredit: string;
  imageFit?: VisualFit;
  imagePosition?: string;
  fact: string;
};

export type Shark = {
  id: string;
  name: string;
  family: string;
  lengthFt: number;
  speedMph: number;
  power: number;
  diet: string;
  image: string;
  imageSourceFile: string;
  imageSourceUrl: string;
  imageCredit: string;
  imageFit?: VisualFit;
  imagePosition?: string;
  fact: string;
};

export type SpaceKind = "planet" | "dwarf planet" | "star" | "concept" | "moon" | "region";

export type SpaceCard = {
  id: string;
  name: string;
  kind: SpaceKind;
  group: string;
  image: string;
  imageSourceFile: string;
  imageSourceUrl: string;
  imageCredit: string;
  imageFit?: VisualFit;
  imagePosition?: string;
  diameterMiles?: number;
  distanceFromSunMillionMiles?: number;
  meanSurfaceTempF?: number;
  surfaceTempK?: number;
  radiusSolar?: number;
  distanceLightYears?: number;
  moons?: number;
  statNote?: string;
  fact: string;
  conceptQuestion?: string;
  conceptAnswer?: string;
};

export type JetCategory = "stealth" | "dogfighter" | "multirole" | "bomber" | "recon" | "attack" | "interceptor" | "trainer";

export type Jet = {
  id: string;
  name: string;
  country: string;
  category: JetCategory;
  maxSpeedMph: number;
  rangeMiles: number;
  firepower: number;
  image: string;
  imageSourceFile: string;
  imageSourceUrl: string;
  imageCredit: string;
  imageFit?: VisualFit;
  imagePosition?: string;
  fact: string;
};

export type TopicPack = {
  id: KnowledgeTopic;
  label: string;
  eyebrow: string;
  roundLabel: string;
  libraryCount: number;
  featuredCount: number;
  sources: { label: string; url: string }[];
  samples: string[];
};

const contentImage = (topic: KnowledgeTopic, id: string, sourceFile: string) => ({
  image: `/burrow-assets/${topic}/${id}.jpg`,
  imageSourceFile: sourceFile,
  imageSourceUrl: `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(sourceFile).replaceAll("%20", "_")}`,
});

export const heatBands: HeatBand[] = ["not spicy", "mild", "warm", "hot", "very hot", "insane"];

export const heatProfiles: Record<HeatBand, { label: string; icons: number; emoji: string; kidLine: string }> = {
  "not spicy": { label: "not spicy", icons: 0, emoji: "no spice", kidLine: "No burn. Easy mode." },
  mild: { label: "mild", icons: 1, emoji: "🌶️", kidLine: "A tiny spicy spark." },
  warm: { label: "warm", icons: 2, emoji: "🌶️🌶️", kidLine: "A friendly spicy kick." },
  hot: { label: "hot", icons: 3, emoji: "🌶️🌶️🌶️", kidLine: "A real spicy kick." },
  "very hot": { label: "very hot", icons: 4, emoji: "🌶️🌶️🌶️🌶️", kidLine: "Tiny bites only." },
  insane: { label: "insane", icons: 5, emoji: "🌶️🌶️🌶️🌶️🌶️🔥", kidLine: "Super-hot legend zone." },
};

export const heatBandForScoville = (shu: number): HeatBand => {
  if (shu <= 500) return "not spicy";
  if (shu <= 2500) return "mild";
  if (shu <= 25000) return "warm";
  if (shu <= 50000) return "hot";
  if (shu <= 500000) return "very hot";
  return "insane";
};

export const heatBandRangeLabel = (heat: HeatBand) => {
  switch (heat) {
    case "not spicy":
      return "0-500 SHU";
    case "mild":
      return "501-2,500 SHU";
    case "warm":
      return "2,501-25,000 SHU";
    case "hot":
      return "25,001-50,000 SHU";
    case "very hot":
      return "50,001-500,000 SHU";
    case "insane":
      return "500,001+ SHU";
  }
};

const pepperSeeds: PepperSeed[] = [
  {
    id: "bell-pepper",
    name: "Bell Pepper",
    shuMin: 0,
    shuMax: 0,
    color: "red",
    ...contentImage("peppers", "bell-pepper", "Red Bell Pepper.jpg"),
    imageCredit: "Bambi Cia, Wikimedia Commons",
    fact: "Bell peppers have 0 Scoville Heat Units. They are sweet, not spicy.",
  },
  {
    id: "banana-pepper",
    name: "Banana Pepper",
    shuMin: 0,
    shuMax: 500,
    color: "yellow",
    ...contentImage("peppers", "banana-pepper", "Banana peppers.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Banana peppers are usually gentle, yellow, and easy to eat.",
  },
  {
    id: "pepperoncini",
    name: "Pepperoncini",
    shuMin: 100,
    shuMax: 500,
    color: "green",
    ...contentImage("peppers", "pepperoncini", "Pepperoncini.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Pepperoncini are tangy peppers with very low heat.",
  },
  {
    id: "poblano",
    name: "Poblano",
    shuMin: 1000,
    shuMax: 2000,
    color: "dark green",
    ...contentImage("peppers", "poblano", "Poblano Pepper.jpg"),
    imageCredit: "stef yau, Wikimedia Commons",
    fact: "Poblanos are gentle peppers often used for chile relleno.",
  },
  {
    id: "anaheim",
    name: "Anaheim",
    shuMin: 500,
    shuMax: 2500,
    color: "green",
    ...contentImage("peppers", "anaheim", "Anaheim Chili Peppers.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Anaheim peppers are long green peppers with a mild kick.",
  },
  {
    id: "jalapeno",
    name: "Jalapeno",
    shuMin: 2500,
    shuMax: 8000,
    color: "green",
    ...contentImage("peppers", "jalapeno", "Jalapeño.jpg"),
    imageCredit: "Eric Polk, Wikimedia Commons",
    fact: "A jalapeno is spicy enough to notice, but not a super-hot.",
  },
  {
    id: "fresno",
    name: "Fresno",
    shuMin: 2500,
    shuMax: 10000,
    color: "red",
    ...contentImage("peppers", "fresno", "Red chili pepper.jpg"),
    imageCredit: "Selimee, Wikimedia Commons",
    fact: "Fresnos look a bit like red jalapenos and can be a little hotter.",
  },
  {
    id: "serrano",
    name: "Serrano",
    shuMin: 10000,
    shuMax: 23000,
    color: "green",
    ...contentImage("peppers", "serrano", "Serrano peppers.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Serranos are usually hotter than jalapenos.",
  },
  {
    id: "cayenne",
    name: "Cayenne",
    shuMin: 30000,
    shuMax: 50000,
    color: "red",
    ...contentImage("peppers", "cayenne", "Cayenne pepper 1.JPG"),
    imageCredit: "Andrew Dalby, Wikimedia Commons",
    fact: "Cayenne peppers are often dried and ground into red pepper powder.",
  },
  {
    id: "tabasco",
    name: "Tabasco",
    shuMin: 30000,
    shuMax: 50000,
    color: "red",
    ...contentImage("peppers", "tabasco", "Tabasco peppers.JPG"),
    imageCredit: "Wikimedia Commons",
    fact: "Tabasco peppers are famous for hot sauce.",
  },
  {
    id: "thai-chili",
    name: "Thai Chili",
    shuMin: 50000,
    shuMax: 100000,
    color: "red",
    ...contentImage("peppers", "thai-chili", "Bird's eye chili.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Thai chilies are small, bright, and much hotter than jalapenos.",
  },
  {
    id: "scotch-bonnet",
    name: "Scotch Bonnet",
    shuMin: 100000,
    shuMax: 350000,
    color: "yellow",
    ...contentImage("peppers", "scotch-bonnet", "Scotch bonnet chili pepper.jpg"),
    imageCredit: "Temaciejewski, Wikimedia Commons",
    fact: "Scotch bonnets are fruity, wrinkly peppers used in Caribbean cooking.",
  },
  {
    id: "habanero",
    name: "Habanero",
    shuMin: 100000,
    shuMax: 350000,
    color: "orange",
    ...contentImage("peppers", "habanero", "Habanero pepper 01.jpg"),
    imageCredit: "Zhayon, Wikimedia Commons",
    fact: "Habaneros are small, fruity, and much hotter than jalapenos.",
  },
  {
    id: "fatalii",
    name: "Fatalii",
    shuMin: 125000,
    shuMax: 400000,
    color: "yellow",
    ...contentImage("peppers", "fatalii", "Fatalii peppers.jpg"),
    imageCredit: "Eric Polk, Wikimedia Commons",
    fact: "Fatalii peppers are yellow super-hot relatives of habaneros.",
  },
  {
    id: "ghost-pepper",
    name: "Ghost Pepper",
    shuMin: 855000,
    shuMax: 1041427,
    color: "red",
    ...contentImage("peppers", "ghost-pepper", "Ghost Pepper ( Bhut Jolokia ).jpg"),
    imageCredit: "Rumi Borah, Wikimedia Commons",
    fact: "Ghost peppers were once famous as the world's hottest pepper.",
  },
  {
    id: "seven-pot-primo",
    name: "7 Pot Primo",
    shuMin: 800000,
    shuMax: 1469000,
    color: "red",
    ...contentImage("peppers", "seven-pot-primo", "Capsicum chinense, Texture.jpg"),
    imageCredit: "Filo gen', Wikimedia Commons",
    fact: "7 Pot Primo peppers are super-hot and often have a pointy tail.",
  },
  {
    id: "trinidad-scorpion",
    name: "Trinidad Moruga Scorpion",
    shuMin: 1200000,
    shuMax: 2000000,
    color: "red",
    ...contentImage("peppers", "trinidad-scorpion", "Trinidad Moruga Scorpion.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Trinidad Moruga Scorpion peppers are named for their stinger-like shape.",
  },
  {
    id: "carolina-reaper",
    name: "Carolina Reaper",
    shuMin: 1400000,
    shuMax: 2200000,
    color: "red",
    ...contentImage("peppers", "carolina-reaper", "Carolina Reaper pepper pods (cropped).jpg"),
    imageCredit: "Dale Thurber, Wikimedia Commons",
    fact: "The Carolina Reaper is a super-hot pepper with a wrinkly red shape.",
  },
  {
    id: "dragons-breath",
    name: "Dragon's Breath",
    shuMin: 2400000,
    shuMax: 2480000,
    color: "red",
    ...contentImage("peppers", "dragons-breath", "Dragon's Breath Pepper.jpg"),
    imageCredit: "Houfescu, Wikimedia Commons",
    fact: "Dragon's Breath is a legendary super-hot pepper name.",
  },
  {
    id: "pepper-x",
    name: "Pepper X",
    shuMin: 2693000,
    shuMax: 2693000,
    color: "greenish yellow",
    ...contentImage("peppers", "pepper-x", "Capsicum chinense.jpg"),
    imageCredit: "Eric in SF, Wikimedia Commons",
    fact: "Pepper X is known for an extremely high Scoville score.",
  },
  {
    id: "shishito",
    name: "Shishito",
    shuMin: 50,
    shuMax: 200,
    color: "green",
    ...contentImage("peppers", "shishito", "Shishito Peppers.jpg"),
    imageCredit: "orchidgalore, Wikimedia Commons",
    fact: "Shishito peppers are usually very mild, but an occasional pepper can surprise you.",
  },
  {
    id: "padron",
    name: "Padron",
    shuMin: 500,
    shuMax: 2500,
    color: "green",
    ...contentImage("peppers", "padron", "Padrón peppers.jpg"),
    imageCredit: "Flickr.Whisker, Wikimedia Commons",
    fact: "Padron peppers are often mild, but some have a sudden spicy bite.",
  },
  {
    id: "ancho",
    name: "Ancho",
    shuMin: 1000,
    shuMax: 2000,
    color: "dark red",
    ...contentImage("peppers", "ancho", "Chile Ancho seco.JPG"),
    imageCredit: "Diogenes el Filosofo, Wikimedia Commons",
    fact: "Ancho chiles are dried poblanos with gentle heat and a deep, sweet flavor.",
  },
  {
    id: "guajillo",
    name: "Guajillo",
    shuMin: 2500,
    shuMax: 5000,
    color: "red",
    ...contentImage("peppers", "guajillo", "Chile Guajillo (5200438953).jpg"),
    imageCredit: "Leslie Seaton, Wikimedia Commons",
    fact: "Guajillo chiles are dried red peppers used in many Mexican sauces.",
  },
  {
    id: "chile-de-arbol",
    name: "Chile de Arbol",
    shuMin: 15000,
    shuMax: 30000,
    color: "red",
    ...contentImage("peppers", "chile-de-arbol", "Mature Chile de arbol peppers.jpg"),
    imageCredit: "Yair Geva, Wikimedia Commons",
    fact: "Chile de arbol peppers are thin, red, and often dried for spicy salsas.",
  },
  {
    id: "aji-amarillo",
    name: "Aji Amarillo",
    shuMin: 30000,
    shuMax: 50000,
    color: "orange",
    ...contentImage("peppers", "aji-amarillo", "Aji Amarillo pepper.jpg"),
    imageCredit: "Luis Tamayo, Wikimedia Commons",
    fact: "Aji amarillo is a bright orange pepper important in Peruvian cooking.",
  },
  {
    id: "rocoto",
    name: "Rocoto",
    shuMin: 30000,
    shuMax: 100000,
    color: "red",
    ...contentImage("peppers", "rocoto", "Rocoto.jpg"),
    imageCredit: "Sebastian Aguilar, Wikimedia Commons",
    fact: "Rocoto peppers can look round like small apples and have black seeds.",
  },
  {
    id: "chiltepin",
    name: "Chiltepin",
    shuMin: 50000,
    shuMax: 100000,
    color: "red",
    ...contentImage("peppers", "chiltepin", "Capsicum annuum Chiltepin 1zz.jpg"),
    imageCredit: "David J. Stang, Wikimedia Commons",
    fact: "Chiltepin is a tiny wild chile with a quick, sharp heat.",
  },
  {
    id: "cubanelle",
    name: "Cubanelle",
    shuMin: 100,
    shuMax: 1000,
    color: "light green",
    ...contentImage("peppers", "cubanelle", "Cubanelle Peppers.jpg"),
    imageCredit: "Forest and Kim Starr, Wikimedia Commons",
    fact: "Cubanelle peppers are sweet frying peppers with only a tiny bit of heat.",
  },
  {
    id: "cherry-pepper",
    name: "Cherry Pepper",
    shuMin: 2500,
    shuMax: 5000,
    color: "red",
    ...contentImage("peppers", "cherry-pepper", "Cherry peppers.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Cherry peppers are round, crisp peppers often stuffed or pickled.",
  },
  {
    id: "pasilla",
    name: "Pasilla",
    shuMin: 1000,
    shuMax: 2500,
    color: "dark brown",
    ...contentImage("peppers", "pasilla", "Capsicum annuum pasilla dried.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Pasilla chiles are dried chilaca peppers with mild heat and a raisin-like flavor.",
  },
  {
    id: "mulato",
    name: "Mulato",
    shuMin: 2500,
    shuMax: 3000,
    color: "brown",
    ...contentImage("peppers", "mulato", "Chile Mulato.JPG"),
    imageCredit: "Diogenes el Filosofo, Wikimedia Commons",
    fact: "Mulato chiles are dried poblanos with darker color and gentle heat.",
  },
  {
    id: "cascabel",
    name: "Cascabel",
    shuMin: 1500,
    shuMax: 2500,
    color: "red-brown",
    ...contentImage("peppers", "cascabel", "Cascabel chile.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Cascabel means little bell, because the dried seeds rattle inside the chile.",
  },
  {
    id: "hatch-chile",
    name: "Hatch Chile",
    shuMin: 1000,
    shuMax: 8000,
    color: "green",
    ...contentImage("peppers", "hatch-chile", "Hatch green chile peppers.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Hatch chiles come from New Mexico's Hatch Valley and can range from mild to hot.",
  },
  {
    id: "new-mexico-chile",
    name: "New Mexico Chile",
    shuMin: 500,
    shuMax: 10000,
    color: "red",
    ...contentImage("peppers", "new-mexico-chile", "New Mexico chile peppers.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "New Mexico chiles are central to red and green chile sauces.",
  },
  {
    id: "datil",
    name: "Datil",
    shuMin: 100000,
    shuMax: 300000,
    color: "orange",
    ...contentImage("peppers", "datil", "Datil.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Datil peppers are fruity hot peppers closely associated with St. Augustine, Florida.",
  },
  {
    id: "manzano",
    name: "Manzano",
    shuMin: 12000,
    shuMax: 30000,
    color: "yellow",
    ...contentImage("peppers", "manzano", "Rocoto pepper.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Manzano peppers are apple-shaped relatives of rocotos with dark seeds.",
  },
  {
    id: "aji-limo",
    name: "Aji Limo",
    shuMin: 30000,
    shuMax: 50000,
    color: "red",
    ...contentImage("peppers", "aji-limo", "Aji limo.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Aji limo is a hot Peruvian chile often used for ceviche.",
  },
  {
    id: "aji-charapita",
    name: "Aji Charapita",
    shuMin: 30000,
    shuMax: 50000,
    color: "yellow",
    ...contentImage("peppers", "aji-charapita", "Aji charapita.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Aji charapita is a tiny Amazonian pepper with bright fruity heat.",
  },
  {
    id: "lemon-drop",
    name: "Lemon Drop",
    shuMin: 15000,
    shuMax: 30000,
    color: "yellow",
    ...contentImage("peppers", "lemon-drop", "Lemon Drop chilli.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Lemon Drop peppers have citrusy flavor and a warm yellow color.",
  },
  {
    id: "bishop-crown",
    name: "Bishop's Crown",
    shuMin: 5000,
    shuMax: 30000,
    color: "red",
    ...contentImage("peppers", "bishop-crown", "Bishop's Crown pepper.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Bishop's Crown peppers have winged sides that look like a little hat.",
  },
  {
    id: "fish-pepper",
    name: "Fish Pepper",
    shuMin: 5000,
    shuMax: 30000,
    color: "striped",
    ...contentImage("peppers", "fish-pepper", "Fish pepper.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Fish peppers have striped leaves and pods and a history in Chesapeake cooking.",
  },
  {
    id: "goat-pepper",
    name: "Goat Pepper",
    shuMin: 100000,
    shuMax: 350000,
    color: "orange",
    ...contentImage("peppers", "goat-pepper", "Bahamian goat pepper.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Goat peppers are Caribbean hot peppers with fruity habanero-like heat.",
  },
  {
    id: "pequin",
    name: "Pequin",
    shuMin: 30000,
    shuMax: 60000,
    color: "red",
    ...contentImage("peppers", "pequin", "Chile Pequin.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Pequin peppers are small, hot chiles often dried for flakes and sauces.",
  },
  {
    id: "naga-viper",
    name: "Naga Viper",
    shuMin: 900000,
    shuMax: 1382118,
    color: "red",
    ...contentImage("peppers", "naga-viper", "Naga Viper pepper.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Naga Viper is a super-hot chile bred from several extremely hot pepper lines.",
  },
  {
    id: "komodo-dragon",
    name: "Komodo Dragon",
    shuMin: 1400000,
    shuMax: 2200000,
    color: "red",
    ...contentImage("peppers", "komodo-dragon", "Komodo Dragon chilli pepper.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Komodo Dragon is a super-hot pepper with delayed heat that builds after the first bite.",
  },
  {
    id: "trinidad-perfume",
    name: "Trinidad Perfume",
    shuMin: 0,
    shuMax: 500,
    color: "yellow",
    ...contentImage("peppers", "trinidad-perfume", "Trinidad Perfume pepper.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Trinidad Perfume has habanero-like aroma with almost no heat.",
  },
  {
    id: "peter-pepper",
    name: "Peter Pepper",
    shuMin: 5000,
    shuMax: 30000,
    color: "red",
    ...contentImage("peppers", "peter-pepper", "Peter pepper.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Peter peppers are odd-shaped heirloom chiles with medium heat.",
  },
  {
    id: "purple-beauty",
    name: "Purple Beauty",
    shuMin: 0,
    shuMax: 0,
    color: "purple",
    ...contentImage("peppers", "purple-beauty", "Purple bell pepper.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Purple Beauty is a sweet bell pepper variety with glossy purple skin.",
  },
  {
    id: "madame-jeanette",
    name: "Madame Jeanette",
    shuMin: 125000,
    shuMax: 325000,
    color: "yellow",
    ...contentImage("peppers", "madame-jeanette", "Madame Jeanette pepper.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Madame Jeanette is a hot, aromatic pepper popular in Surinamese cooking.",
  },
];

export const peppers = pepperSeeds.map((pepper) => ({
  ...pepper,
  heat: heatBandForScoville(pepper.shuMax),
}));

export const buildings: Building[] = [
  {
    id: "burj-khalifa",
    name: "Burj Khalifa",
    city: "Dubai",
    country: "United Arab Emirates",
    heightFt: 2717,
    floors: 163,
    status: "finished",
    ...contentImage("buildings", "burj-khalifa", "Burj Khalifa (16260269606).jpg"),
    imageCredit: "Wikimedia Commons",
    imagePosition: "center bottom",
    fact: "Burj Khalifa is the tallest finished building in the world.",
  },
  {
    id: "merdeka-118",
    name: "Merdeka 118",
    city: "Kuala Lumpur",
    country: "Malaysia",
    heightFt: 2227,
    floors: 118,
    status: "finished",
    ...contentImage("buildings", "merdeka-118", "Merdeka 118 in September 2024.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Merdeka 118 is the second tallest finished building in the world.",
  },
  {
    id: "shanghai-tower",
    name: "Shanghai Tower",
    city: "Shanghai",
    country: "China",
    heightFt: 2073,
    floors: 128,
    status: "finished",
    ...contentImage("buildings", "shanghai-tower", "Shanghai Tower.jpg"),
    imageCredit: "Baycrest, Wikimedia Commons",
    fact: "Shanghai Tower twists as it rises into the sky.",
  },
  {
    id: "makkah-clock",
    name: "Makkah Royal Clock Tower",
    city: "Mecca",
    country: "Saudi Arabia",
    heightFt: 1972,
    floors: 120,
    status: "finished",
    ...contentImage("buildings", "makkah-clock", "Abraj-al-Bait largest clock tower ever.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "This tower has a huge clock near the top.",
  },
  {
    id: "ping-an",
    name: "Ping An Finance Centre",
    city: "Shenzhen",
    country: "China",
    heightFt: 1965,
    floors: 115,
    status: "finished",
    ...contentImage("buildings", "ping-an", "Pingan International Finance Center2020.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Ping An Finance Centre is one of China's tallest skyscrapers.",
  },
  {
    id: "lotte-world-tower",
    name: "Lotte World Tower",
    city: "Seoul",
    country: "South Korea",
    heightFt: 1819,
    floors: 123,
    status: "finished",
    ...contentImage("buildings", "lotte-world-tower", "Lotte World Tower near Cheongdam Bridge.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Lotte World Tower is a supertall skyscraper in Seoul.",
  },
  {
    id: "one-wtc",
    name: "One World Trade Center",
    city: "New York City",
    country: "United States",
    heightFt: 1776,
    floors: 94,
    status: "finished",
    ...contentImage("buildings", "one-wtc", "One World Trade Center May 2015.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "One World Trade Center is 1,776 feet tall, matching the year 1776.",
  },
  {
    id: "guangzhou-ctf",
    name: "Guangzhou CTF Finance Centre",
    city: "Guangzhou",
    country: "China",
    heightFt: 1739,
    floors: 111,
    status: "finished",
    ...contentImage("buildings", "guangzhou-ctf", "Guangzhou CTF Finance Centre.jpg"),
    imageCredit: "Wikimedia Commons",
    imageFit: "contain",
    fact: "Guangzhou CTF is a very tall tower in southern China.",
  },
  {
    id: "tianjin-ctf",
    name: "Tianjin CTF Finance Centre",
    city: "Tianjin",
    country: "China",
    heightFt: 1739,
    floors: 97,
    status: "finished",
    ...contentImage("buildings", "tianjin-ctf", "Tianjin CTF Finance Centre in 2019.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Tianjin CTF has a smooth, curving shape.",
  },
  {
    id: "china-zun",
    name: "CITIC Tower",
    city: "Beijing",
    country: "China",
    heightFt: 1731,
    floors: 109,
    status: "finished",
    ...contentImage("buildings", "china-zun", "CITIC Tower 2021.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "CITIC Tower is also called China Zun.",
  },
  {
    id: "taipei-101",
    name: "Taipei 101",
    city: "Taipei",
    country: "Taiwan",
    heightFt: 1667,
    floors: 101,
    status: "finished",
    ...contentImage("buildings", "taipei-101", "Taipei 101 2009 amk.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Taipei 101 has stacked sections that look like giant blocks.",
  },
  {
    id: "shanghai-wfc",
    name: "Shanghai World Financial Center",
    city: "Shanghai",
    country: "China",
    heightFt: 1614,
    floors: 101,
    status: "finished",
    ...contentImage("buildings", "shanghai-wfc", "Shanghai World Financial Center.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "This building has a big opening near the top.",
  },
  {
    id: "icc",
    name: "International Commerce Centre",
    city: "Hong Kong",
    country: "China",
    heightFt: 1588,
    floors: 108,
    status: "finished",
    ...contentImage("buildings", "icc", "International Commerce Centre 201008.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "The ICC is one of Hong Kong's tallest buildings.",
  },
  {
    id: "central-park-tower",
    name: "Central Park Tower",
    city: "New York City",
    country: "United States",
    heightFt: 1550,
    floors: 98,
    status: "finished",
    ...contentImage("buildings", "central-park-tower", "Central Park Tower April 2021.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Central Park Tower is an extremely tall residential building.",
  },
  {
    id: "lakhta-center",
    name: "Lakhta Center",
    city: "Saint Petersburg",
    country: "Russia",
    heightFt: 1516,
    floors: 87,
    status: "finished",
    ...contentImage("buildings", "lakhta-center", "Lakhta Center July 2019.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Lakhta Center is the tallest building in Europe.",
  },
  {
    id: "landmark-81",
    name: "Landmark 81",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    heightFt: 1513,
    floors: 81,
    status: "finished",
    ...contentImage("buildings", "landmark-81", "Landmark 81 in 2021.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Landmark 81 is Vietnam's tallest skyscraper.",
  },
  {
    id: "petronas-towers",
    name: "Petronas Towers",
    city: "Kuala Lumpur",
    country: "Malaysia",
    heightFt: 1483,
    floors: 88,
    status: "finished",
    ...contentImage("buildings", "petronas-towers", "KL-Petronas Towers at dusk.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "The Petronas Towers are twin towers connected by a skybridge.",
  },
  {
    id: "willis-tower",
    name: "Willis Tower",
    city: "Chicago",
    country: "United States",
    heightFt: 1451,
    floors: 108,
    status: "finished",
    ...contentImage("buildings", "willis-tower", "Willis Tower From Lake.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Willis Tower was once the tallest building in the world.",
  },
  {
    id: "432-park",
    name: "432 Park Avenue",
    city: "New York City",
    country: "United States",
    heightFt: 1396,
    floors: 85,
    status: "finished",
    ...contentImage("buildings", "432-park", "432 Park Avenue, NY.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "432 Park Avenue is a very skinny tower in New York.",
  },
  {
    id: "jeddah-tower",
    name: "Jeddah Tower",
    city: "Jeddah",
    country: "Saudi Arabia",
    heightFt: 3281,
    floors: 167,
    status: "under construction",
    ...contentImage("buildings", "jeddah-tower", "Jeddah Tower August 2019 S.Nitzold.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Jeddah Tower is planned to be more than 3,000 feet tall when finished.",
  },
  {
    id: "wuhan-greenland-center",
    name: "Wuhan Greenland Center",
    city: "Wuhan",
    country: "China",
    heightFt: 1560,
    floors: 101,
    status: "finished",
    ...contentImage("buildings", "wuhan-greenland-center", "Wuhan Greenland Center.jpg"),
    imageCredit: "Aangkianghai, Wikimedia Commons",
    fact: "Wuhan Greenland Center was redesigned shorter than first planned but still rises over 1,500 feet.",
  },
  {
    id: "111-west-57th",
    name: "111 West 57th Street",
    city: "New York City",
    country: "United States",
    heightFt: 1428,
    floors: 84,
    status: "finished",
    ...contentImage("buildings", "111-west-57th", "111 West 57th Street.jpg"),
    imageCredit: "Kidfly182, Wikimedia Commons",
    fact: "111 West 57th Street is a very slender residential tower beside historic Steinway Hall.",
  },
  {
    id: "one-vanderbilt",
    name: "One Vanderbilt",
    city: "New York City",
    country: "United States",
    heightFt: 1401,
    floors: 73,
    status: "finished",
    ...contentImage("buildings", "one-vanderbilt", "One Vanderbilt.jpg"),
    imageCredit: "Kidfly182, Wikimedia Commons",
    fact: "One Vanderbilt stands next to Grand Central Terminal in Midtown Manhattan.",
  },
  {
    id: "jin-mao",
    name: "Jin Mao Tower",
    city: "Shanghai",
    country: "China",
    heightFt: 1380,
    floors: 88,
    status: "finished",
    ...contentImage("buildings", "jin-mao", "Jin Mao Tower.JPG"),
    imageCredit: "Christof Berger, Wikimedia Commons",
    fact: "Jin Mao Tower uses tiered shapes inspired by traditional Chinese architecture.",
  },
  {
    id: "princess-tower",
    name: "Princess Tower",
    city: "Dubai",
    country: "United Arab Emirates",
    heightFt: 1356,
    floors: 101,
    status: "finished",
    ...contentImage("buildings", "princess-tower", "Dubai Marina (8973482466).jpg"),
    imageCredit: "Fabio Achilli, Wikimedia Commons",
    fact: "Princess Tower is a very tall residential skyscraper in Dubai Marina.",
  },
  {
    id: "empire-state",
    name: "Empire State Building",
    city: "New York City",
    country: "United States",
    heightFt: 1250,
    floors: 102,
    status: "finished",
    ...contentImage("buildings", "empire-state", "Empire State Building.png"),
    imageCredit: "NegweS, Wikimedia Commons",
    fact: "The Empire State Building was the world's tallest building for decades after opening in 1931.",
  },
  {
    id: "270-park-avenue",
    name: "270 Park Avenue",
    city: "New York City",
    country: "United States",
    heightFt: 1388,
    floors: 60,
    status: "finished",
    ...contentImage("buildings", "270-park-avenue", "270parkave from empirestate 03 14 2025 (cropped).jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "270 Park Avenue is JPMorgan Chase's new all-electric global headquarters in Midtown Manhattan.",
  },
  {
    id: "30-hudson-yards",
    name: "30 Hudson Yards",
    city: "New York City",
    country: "United States",
    heightFt: 1270,
    floors: 73,
    status: "finished",
    ...contentImage("buildings", "30-hudson-yards", "Hudson Yards from Hudson Commons (95131p) (30 Hudson Yards).jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "30 Hudson Yards has a sky deck that juts out high above Manhattan.",
  },
  {
    id: "bank-of-america-tower-nyc",
    name: "Bank of America Tower",
    city: "New York City",
    country: "United States",
    heightFt: 1200,
    floors: 55,
    status: "finished",
    ...contentImage("buildings", "bank-of-america-tower-nyc", "Bank of America Tower in Manhattan 2015.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Bank of America Tower was an early New York skyscraper to earn Platinum LEED certification.",
  },
  {
    id: "3-world-trade-center",
    name: "3 World Trade Center",
    city: "New York City",
    country: "United States",
    heightFt: 1079,
    floors: 80,
    status: "finished",
    ...contentImage("buildings", "3-world-trade-center", "Looking up at 3 and 4 World Trade Center (cropped).jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "3 World Trade Center is one of the tallest buildings in Lower Manhattan.",
  },
  {
    id: "brooklyn-tower",
    name: "Brooklyn Tower",
    city: "New York City",
    country: "United States",
    heightFt: 1066,
    floors: 74,
    status: "finished",
    ...contentImage("buildings", "brooklyn-tower", "The Brooklyn Tower 010.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Brooklyn Tower is the tallest building in Brooklyn and rises from the historic Dime Savings Bank site.",
  },
  {
    id: "53w53",
    name: "53W53",
    city: "New York City",
    country: "United States",
    heightFt: 1050,
    floors: 77,
    status: "finished",
    ...contentImage("buildings", "53w53", "53w53Aug9.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "53W53 is a tapered residential tower next to the Museum of Modern Art.",
  },
  {
    id: "chrysler-building",
    name: "Chrysler Building",
    city: "New York City",
    country: "United States",
    heightFt: 1046,
    floors: 77,
    status: "finished",
    ...contentImage("buildings", "chrysler-building", "Chrysler Building by David Shankbone Retouched.jpg"),
    imageCredit: "David Shankbone, Wikimedia Commons",
    fact: "The Chrysler Building is famous for its shiny Art Deco crown.",
  },
  {
    id: "new-york-times-building",
    name: "The New York Times Building",
    city: "New York City",
    country: "United States",
    heightFt: 1046,
    floors: 52,
    status: "finished",
    ...contentImage("buildings", "new-york-times-building", "New York Times Tower from NYTD.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "The New York Times Building uses ceramic rods on its facade to help shade the glass.",
  },
  {
    id: "the-spiral",
    name: "The Spiral",
    city: "New York City",
    country: "United States",
    heightFt: 1031,
    floors: 66,
    status: "finished",
    ...contentImage("buildings", "the-spiral", "The Spiral Sep 2021.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "The Spiral has outdoor terraces that step around the tower as it rises.",
  },
  {
    id: "one57",
    name: "One57",
    city: "New York City",
    country: "United States",
    heightFt: 1004,
    floors: 75,
    status: "finished",
    ...contentImage("buildings", "one57", "One57 from Columbus Circle, May 2014.png"),
    imageCredit: "Wikimedia Commons",
    fact: "One57 was one of the first supertall residential towers on Billionaires' Row.",
  },
  {
    id: "4-world-trade-center",
    name: "4 World Trade Center",
    city: "New York City",
    country: "United States",
    heightFt: 977,
    floors: 72,
    status: "finished",
    ...contentImage("buildings", "4-world-trade-center", "4 World Trade Center 048.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "4 World Trade Center is a glassy tower in the rebuilt World Trade Center complex.",
  },
  {
    id: "brooklyn-point",
    name: "Brooklyn Point",
    city: "New York City",
    country: "United States",
    heightFt: 720,
    floors: 68,
    status: "finished",
    ...contentImage("buildings", "brooklyn-point", "BrooklynPointII.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Brooklyn Point was Brooklyn's tallest building before Brooklyn Tower took the title.",
  },
  {
    id: "ava-dobro",
    name: "AVA DoBro",
    city: "New York City",
    country: "United States",
    heightFt: 624,
    floors: 58,
    status: "finished",
    ...contentImage("buildings", "ava-dobro", "AVADobro1.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "AVA DoBro is a tall residential tower in Downtown Brooklyn.",
  },
  {
    id: "11-hoyt",
    name: "11 Hoyt",
    city: "New York City",
    country: "United States",
    heightFt: 618,
    floors: 54,
    status: "finished",
    ...contentImage("buildings", "11-hoyt", "11 Hoyt 007.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "11 Hoyt rises from the former Macy's footprint in Downtown Brooklyn.",
  },
  {
    id: "the-everly",
    name: "The Everly",
    city: "New York City",
    country: "United States",
    heightFt: 610,
    floors: 49,
    status: "under construction",
    ...contentImage("buildings", "the-everly", "Fort Greene Brooklyn November 2024 001.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "The Everly is one of Brooklyn's tallest topped-out residential towers.",
  },
  {
    id: "bank-of-china",
    name: "Bank of China Tower",
    city: "Hong Kong",
    country: "China",
    heightFt: 1205,
    floors: 72,
    status: "finished",
    ...contentImage("buildings", "bank-of-china", "Bank of China Tower (Hong Kong).jpg"),
    imageCredit: "Mk2010, Wikimedia Commons",
    fact: "Bank of China Tower was designed by I. M. Pei and has sharp triangular shapes.",
  },
];

export const sharks: Shark[] = [
  {
    id: "great-white",
    name: "Great White Shark",
    family: "Mackerel shark",
    lengthFt: 21,
    speedMph: 35,
    power: 5,
    diet: "seals, fish, rays",
    ...contentImage("sharks", "great-white", "White shark.jpg"),
    imageCredit: "Terry Goss, Wikimedia Commons",
    fact: "Great whites are apex predators and can grow to about 21 feet.",
  },
  {
    id: "whale-shark",
    name: "Whale Shark",
    family: "Carpet shark",
    lengthFt: 40,
    speedMph: 3,
    power: 1,
    diet: "plankton",
    ...contentImage("sharks", "whale-shark", "Whale Shark in Shallow Water.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Whale sharks are the biggest fish, but they filter-feed on tiny plankton.",
  },
  {
    id: "tiger-shark",
    name: "Tiger Shark",
    family: "Requiem shark",
    lengthFt: 18,
    speedMph: 20,
    power: 5,
    diet: "fish, turtles, birds",
    ...contentImage("sharks", "tiger-shark", "HIHWNMS tiger shark (50199857407).jpg"),
    imageCredit: "NOAA, Wikimedia Commons",
    fact: "Tiger sharks have stripes when young and are powerful ocean hunters.",
  },
  {
    id: "great-hammerhead",
    name: "Great Hammerhead",
    family: "Hammerhead shark",
    lengthFt: 20,
    speedMph: 25,
    power: 4,
    diet: "rays, fish, squid",
    ...contentImage("sharks", "great-hammerhead", "Great hammerhead nmfs.jpg"),
    imageCredit: "NOAA NMFS Mississippi Laboratory, Wikimedia Commons",
    fact: "Hammerheads use their wide heads like a sensor bar to find prey.",
  },
  {
    id: "shortfin-mako",
    name: "Shortfin Mako",
    family: "Mackerel shark",
    lengthFt: 13,
    speedMph: 43,
    power: 4,
    diet: "fast fish, squid",
    ...contentImage("sharks", "shortfin-mako", "Atlantic Shortfin mako.jpg"),
    imageCredit: "NOAA, Wikimedia Commons",
    fact: "Shortfin makos are among the fastest sharks in the ocean.",
  },
  {
    id: "basking-shark",
    name: "Basking Shark",
    family: "Basking shark",
    lengthFt: 40,
    speedMph: 4,
    power: 1,
    diet: "plankton",
    ...contentImage("sharks", "basking-shark", "Basking Shark.jpg"),
    imageCredit: "Chris Gotschalk, Wikimedia Commons",
    fact: "Basking sharks are huge filter-feeders with giant mouths.",
  },
  {
    id: "nurse-shark",
    name: "Nurse Shark",
    family: "Nurse shark",
    lengthFt: 10,
    speedMph: 5,
    power: 2,
    diet: "crabs, fish, mollusks",
    ...contentImage("sharks", "nurse-shark", "Nurse shark.jpg"),
    imageCredit: "NOAA, Wikimedia Commons",
    fact: "Nurse sharks often rest on the seafloor during the day.",
  },
  {
    id: "zebra-shark",
    name: "Zebra Shark",
    family: "Carpet shark",
    lengthFt: 12,
    speedMph: 5,
    power: 2,
    diet: "shellfish, small fish",
    ...contentImage("sharks", "zebra-shark", "Zebra shark.jpg"),
    imageCredit: "DaraKero_F, Wikimedia Commons",
    fact: "Young zebra sharks have stripes, but adults have spots.",
  },
  {
    id: "goblin-shark",
    name: "Goblin Shark",
    family: "Goblin shark",
    lengthFt: 13,
    speedMph: 10,
    power: 3,
    diet: "deep-sea fish, squid",
    ...contentImage("sharks", "goblin-shark", "Goblin shark, Pengo.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Goblin sharks live deep in the ocean and have a long nose.",
  },
  {
    id: "common-thresher",
    name: "Common Thresher",
    family: "Thresher shark",
    lengthFt: 20,
    speedMph: 30,
    power: 4,
    diet: "schooling fish",
    ...contentImage("sharks", "common-thresher", "Thresher shark - 3.jpg"),
    imageCredit: "Oleg Yunakov, Wikimedia Commons",
    fact: "Thresher sharks use their long tails like a whip to stun fish.",
  },
  {
    id: "blue-shark",
    name: "Blue Shark",
    family: "Requiem shark",
    lengthFt: 12,
    speedMph: 24,
    power: 3,
    diet: "fish, squid",
    ...contentImage("sharks", "blue-shark", "Blue shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Blue sharks are sleek open-ocean travelers.",
  },
  {
    id: "bull-shark",
    name: "Bull Shark",
    family: "Requiem shark",
    lengthFt: 11,
    speedMph: 25,
    power: 5,
    diet: "fish, dolphins, other sharks",
    ...contentImage("sharks", "bull-shark", "Requin bouledogue (Carcharhinus leucas) (Ifremer 00813-92510 - 53591).jpg"),
    imageCredit: "Ifremer, Wikimedia Commons",
    fact: "Bull sharks can swim in both salt water and fresh water.",
  },
  {
    id: "lemon-shark",
    name: "Lemon Shark",
    family: "Requiem shark",
    lengthFt: 11,
    speedMph: 20,
    power: 3,
    diet: "fish, rays, crustaceans",
    ...contentImage("sharks", "lemon-shark", "Lemonshark.jpg"),
    imageCredit: "Albert kok, Wikimedia Commons",
    fact: "Lemon sharks get their name from their yellow-brown color.",
  },
  {
    id: "blacktip-reef",
    name: "Blacktip Reef Shark",
    family: "Requiem shark",
    lengthFt: 6,
    speedMph: 20,
    power: 2,
    diet: "reef fish",
    ...contentImage("sharks", "blacktip-reef", "Blacktip reef shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Blacktip reef sharks patrol warm coral reefs.",
  },
  {
    id: "greenland-shark",
    name: "Greenland Shark",
    family: "Sleeper shark",
    lengthFt: 24,
    speedMph: 2,
    power: 3,
    diet: "fish, seals, carrion",
    ...contentImage("sharks", "greenland-shark", "Greenland shark profile.jpg"),
    imageCredit: "Hemming1952, Wikimedia Commons",
    fact: "Greenland sharks are slow, cold-water sharks that can live for centuries.",
  },
  {
    id: "sawshark",
    name: "Sawshark",
    family: "Sawshark",
    lengthFt: 5,
    speedMph: 10,
    power: 2,
    diet: "small fish, crustaceans",
    ...contentImage("sharks", "sawshark", "Pristiophorus japonicus 2.jpg"),
    imageCredit: "ume-y, Wikimedia Commons",
    fact: "Sawsharks have a long saw-like snout with teeth on the sides.",
  },
  {
    id: "epaulette-shark",
    name: "Epaulette Shark",
    family: "Carpet shark",
    lengthFt: 3,
    speedMph: 2,
    power: 1,
    diet: "worms, crabs, tiny fish",
    ...contentImage("sharks", "epaulette-shark", "Epaulette shark camden.jpg"),
    imageCredit: "Yzx, Wikimedia Commons",
    fact: "Epaulette sharks can wiggle across shallow reef flats.",
  },
  {
    id: "cookiecutter",
    name: "Cookiecutter Shark",
    family: "Sleeper shark",
    lengthFt: 2,
    speedMph: 7,
    power: 3,
    diet: "round bites from big animals",
    ...contentImage("sharks", "cookiecutter", "Cookiecutter shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Cookiecutter sharks take round cookie-shaped bites.",
  },
  {
    id: "sand-tiger",
    name: "Sand Tiger Shark",
    family: "Sand tiger shark",
    lengthFt: 10,
    speedMph: 12,
    power: 3,
    diet: "fish, squid, small sharks",
    ...contentImage("sharks", "sand-tiger", "Sand Tiger Shark.jpg"),
    imageCredit: "Maniacduhockey, Wikimedia Commons",
    fact: "Sand tiger sharks look toothy and fierce, but they are slow coastal hunters.",
  },
  {
    id: "oceanic-whitetip",
    name: "Oceanic Whitetip Shark",
    family: "Requiem shark",
    lengthFt: 13,
    speedMph: 20,
    power: 4,
    diet: "fish, squid, seabirds",
    ...contentImage("sharks", "oceanic-whitetip", "Oceanic Whitetip Shark (cropped).jpg"),
    imageCredit: "Johanlantz, Wikimedia Commons",
    fact: "Oceanic whitetips cruise warm open oceans and have rounded white-tipped fins.",
  },
  {
    id: "scalloped-hammerhead",
    name: "Scalloped Hammerhead",
    family: "Hammerhead shark",
    lengthFt: 14,
    speedMph: 25,
    power: 4,
    diet: "fish, squid, rays",
    ...contentImage("sharks", "scalloped-hammerhead", "Scalloped Hammerheads.jpg"),
    imageCredit: "Stealthwater, Wikimedia Commons",
    fact: "Scalloped hammerheads can gather in large schools around seamounts and islands.",
  },
  {
    id: "frilled-shark",
    name: "Frilled Shark",
    family: "Frilled shark",
    lengthFt: 7,
    speedMph: 3,
    power: 2,
    diet: "squid, fish",
    ...contentImage("sharks", "frilled-shark", "Frilled shark head.jpg"),
    imageCredit: "saname777, Wikimedia Commons",
    fact: "Frilled sharks are deep-water sharks with an eel-like body and frilly gill slits.",
  },
  {
    id: "megamouth",
    name: "Megamouth Shark",
    family: "Megamouth shark",
    lengthFt: 18,
    speedMph: 2,
    power: 1,
    diet: "plankton, krill",
    ...contentImage("sharks", "megamouth", "Megamouthshark.jpg"),
    imageCredit: "Maffeth Opiana, Wikimedia Commons",
    fact: "Megamouth sharks are rare filter-feeders with huge mouths.",
  },
  {
    id: "silky-shark",
    name: "Silky Shark",
    family: "Requiem shark",
    lengthFt: 11,
    speedMph: 20,
    power: 4,
    diet: "fish, squid",
    ...contentImage("sharks", "silky-shark", "Silky shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Silky sharks are smooth-skinned open-ocean hunters often found near tuna schools.",
  },
  {
    id: "spinner-shark",
    name: "Spinner Shark",
    family: "Requiem shark",
    lengthFt: 10,
    speedMph: 29,
    power: 3,
    diet: "schooling fish",
    ...contentImage("sharks", "spinner-shark", "Spinner shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Spinner sharks can leap from the water while spinning after fast-moving fish.",
  },
  {
    id: "dusky-shark",
    name: "Dusky Shark",
    family: "Requiem shark",
    lengthFt: 14,
    speedMph: 20,
    power: 4,
    diet: "fish, rays, squid",
    ...contentImage("sharks", "dusky-shark", "Dusky shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Dusky sharks are large coastal and offshore sharks that mature slowly.",
  },
  {
    id: "sandbar-shark",
    name: "Sandbar Shark",
    family: "Requiem shark",
    lengthFt: 8,
    speedMph: 18,
    power: 3,
    diet: "fish, crabs, rays",
    ...contentImage("sharks", "sandbar-shark", "Carcharhinus plumbeus.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Sandbar sharks have tall dorsal fins and often cruise near sandy coastal bottoms.",
  },
  {
    id: "galapagos-shark",
    name: "Galapagos Shark",
    family: "Requiem shark",
    lengthFt: 12,
    speedMph: 20,
    power: 4,
    diet: "fish, squid, rays",
    ...contentImage("sharks", "galapagos-shark", "Galapagos shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Galapagos sharks often gather around oceanic islands and reefs.",
  },
  {
    id: "whitetip-reef",
    name: "Whitetip Reef Shark",
    family: "Requiem shark",
    lengthFt: 7,
    speedMph: 15,
    power: 2,
    diet: "reef fish, octopus, crustaceans",
    ...contentImage("sharks", "whitetip-reef", "Triaenodon obesus hawaii.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Whitetip reef sharks often rest in caves during the day and hunt at night.",
  },
  {
    id: "grey-reef-shark",
    name: "Grey Reef Shark",
    family: "Requiem shark",
    lengthFt: 8,
    speedMph: 25,
    power: 3,
    diet: "reef fish, squid",
    ...contentImage("sharks", "grey-reef-shark", "Grey reef shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Grey reef sharks patrol reef drop-offs and can show bold threat displays.",
  },
  {
    id: "porbeagle",
    name: "Porbeagle",
    family: "Mackerel shark",
    lengthFt: 12,
    speedMph: 20,
    power: 4,
    diet: "fish, squid",
    ...contentImage("sharks", "porbeagle", "Porbeagle shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Porbeagles are cold-water relatives of makos and great whites.",
  },
  {
    id: "salmon-shark",
    name: "Salmon Shark",
    family: "Mackerel shark",
    lengthFt: 10,
    speedMph: 45,
    power: 4,
    diet: "salmon, squid, fish",
    ...contentImage("sharks", "salmon-shark", "Salmon shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Salmon sharks are powerful North Pacific hunters that can keep warm in cold water.",
  },
  {
    id: "longfin-mako",
    name: "Longfin Mako",
    family: "Mackerel shark",
    lengthFt: 14,
    speedMph: 35,
    power: 4,
    diet: "fish, squid",
    ...contentImage("sharks", "longfin-mako", "Longfin mako shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Longfin makos are rarer, longer-finned cousins of the shortfin mako.",
  },
  {
    id: "bigeye-thresher",
    name: "Bigeye Thresher",
    family: "Thresher shark",
    lengthFt: 16,
    speedMph: 25,
    power: 4,
    diet: "fish, squid",
    ...contentImage("sharks", "bigeye-thresher", "Bigeye thresher shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Bigeye threshers have huge eyes for hunting in dim water.",
  },
  {
    id: "pelagic-thresher",
    name: "Pelagic Thresher",
    family: "Thresher shark",
    lengthFt: 12,
    speedMph: 25,
    power: 4,
    diet: "schooling fish",
    ...contentImage("sharks", "pelagic-thresher", "Pelagic Thresher Shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Pelagic threshers use their long tail fins to strike fish in open water.",
  },
  {
    id: "bonnethead",
    name: "Bonnethead",
    family: "Hammerhead shark",
    lengthFt: 5,
    speedMph: 15,
    power: 2,
    diet: "crabs, shrimp, seagrass",
    ...contentImage("sharks", "bonnethead", "Bonnethead shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Bonnetheads are small hammerheads that can digest seagrass as part of their diet.",
  },
  {
    id: "smooth-hammerhead",
    name: "Smooth Hammerhead",
    family: "Hammerhead shark",
    lengthFt: 16,
    speedMph: 25,
    power: 4,
    diet: "fish, squid, rays",
    ...contentImage("sharks", "smooth-hammerhead", "Smooth hammerhead shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Smooth hammerheads lack the central notch seen on scalloped hammerhead heads.",
  },
  {
    id: "horn-shark",
    name: "Horn Shark",
    family: "Bullhead shark",
    lengthFt: 4,
    speedMph: 5,
    power: 1,
    diet: "urchins, crabs, mollusks",
    ...contentImage("sharks", "horn-shark", "Horn shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Horn sharks have blunt heads, fin spines, and strong teeth for crushing shells.",
  },
  {
    id: "port-jackson-shark",
    name: "Port Jackson Shark",
    family: "Bullhead shark",
    lengthFt: 5,
    speedMph: 5,
    power: 1,
    diet: "shellfish, sea urchins",
    ...contentImage("sharks", "port-jackson-shark", "Port Jackson shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Port Jackson sharks lay spiral egg cases that can wedge into rocks.",
  },
  {
    id: "spotted-wobbegong",
    name: "Spotted Wobbegong",
    family: "Carpet shark",
    lengthFt: 10,
    speedMph: 3,
    power: 3,
    diet: "fish, octopus, crustaceans",
    ...contentImage("sharks", "spotted-wobbegong", "Spotted wobbegong.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Wobbegongs are camouflaged carpet sharks that ambush prey from the seafloor.",
  },
  {
    id: "angelshark",
    name: "Angelshark",
    family: "Angel shark",
    lengthFt: 8,
    speedMph: 8,
    power: 3,
    diet: "fish, crustaceans",
    ...contentImage("sharks", "angelshark", "Squatina squatina tenerife.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Angelsharks are flattened ambush predators that can hide under sand.",
  },
  {
    id: "pyjama-shark",
    name: "Pyjama Shark",
    family: "Catshark",
    lengthFt: 4,
    speedMph: 5,
    power: 1,
    diet: "small fish, squid, crustaceans",
    ...contentImage("sharks", "pyjama-shark", "Pyjama shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Pyjama sharks have bold dark stripes that look like pajama patterns.",
  },
  {
    id: "bamboo-shark",
    name: "Brownbanded Bamboo Shark",
    family: "Carpet shark",
    lengthFt: 4,
    speedMph: 4,
    power: 1,
    diet: "small fish, worms, crustaceans",
    ...contentImage("sharks", "bamboo-shark", "Chiloscyllium punctatum.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Brownbanded bamboo sharks are slender reef sharks that often live near coral and sand.",
  },
  {
    id: "caribbean-reef",
    name: "Caribbean Reef Shark",
    family: "Requiem shark",
    lengthFt: 10,
    speedMph: 20,
    power: 3,
    diet: "reef fish, rays",
    ...contentImage("sharks", "caribbean-reef", "Caribbean reef shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Caribbean reef sharks are common large predators on western Atlantic reefs.",
  },
  {
    id: "silvertip-shark",
    name: "Silvertip Shark",
    family: "Requiem shark",
    lengthFt: 10,
    speedMph: 20,
    power: 4,
    diet: "fish, rays, small sharks",
    ...contentImage("sharks", "silvertip-shark", "Silvertip shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Silvertip sharks have bright white edges on several fins.",
  },
  {
    id: "swell-shark",
    name: "Swell Shark",
    family: "Catshark",
    lengthFt: 3,
    speedMph: 4,
    power: 1,
    diet: "small fish, crustaceans",
    ...contentImage("sharks", "swell-shark", "Cephaloscyllium ventriosum.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Swell sharks can gulp water to puff themselves up when threatened.",
  },
  {
    id: "zambezi-shark",
    name: "Zambezi Shark",
    family: "Requiem shark",
    lengthFt: 11,
    speedMph: 25,
    power: 5,
    diet: "fish, turtles, mammals",
    ...contentImage("sharks", "zambezi-shark", "Zambezi shark.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Zambezi shark is another common name for the bull shark in parts of Africa.",
  },
  {
    id: "stethacanthus",
    name: "Stethacanthus",
    family: "Extinct symmoriid shark",
    lengthFt: 6,
    speedMph: 8,
    power: 2,
    diet: "small fish and sea animals",
    ...contentImage("sharks", "stethacanthus", "StethacanthusesDB 2.jpg"),
    imageCredit: "Dmitry Bogdanov, Wikimedia Commons",
    fact: "Stethacanthus was a prehistoric shark relative with a strange, anvil-shaped dorsal fin.",
  },
  {
    id: "megalodon",
    name: "Megalodon",
    family: "Extinct megatooth shark",
    lengthFt: 65,
    speedMph: 20,
    power: 5,
    diet: "whales, large sea animals",
    ...contentImage("sharks", "megalodon", "Megalodon model at the NMNH.jpg"),
    imageCredit: "Ryan Schwark, Wikimedia Commons",
    fact: "Megalodon was an extinct giant shark known mostly from fossil teeth.",
  },
  {
    id: "dunkleosteus",
    name: "Dunkleosteus",
    family: "Armored placoderm",
    lengthFt: 13,
    speedMph: 10,
    power: 5,
    diet: "fish and other sea animals",
    ...contentImage("sharks", "dunkleosteus", "Dunkleosteus skull QM email.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Dunkleosteus was not a shark; it was an armored Devonian fish and early apex predator.",
  },
];

export const spaceCards: SpaceCard[] = [
  {
    id: "venus",
    name: "Venus",
    kind: "planet",
    group: "Solar System",
    diameterMiles: 7521,
    distanceFromSunMillionMiles: 67,
    meanSurfaceTempF: 872,
    moons: 0,
    ...contentImage("space", "venus", "Venus globe.jpg"),
    imageCredit: "NASA/JPL, Wikimedia Commons",
    fact: "Venus is the hottest planet in the solar system because its thick atmosphere traps heat.",
  },
  {
    id: "mars",
    name: "Mars",
    kind: "planet",
    group: "Solar System",
    diameterMiles: 4212,
    distanceFromSunMillionMiles: 142,
    meanSurfaceTempF: -85,
    moons: 2,
    ...contentImage("space", "mars", "OSIRIS Mars true color.jpg"),
    imageCredit: "ESA/Rosetta/OSIRIS, Wikimedia Commons",
    fact: "Mars is cold, dusty, and has two tiny moons named Phobos and Deimos.",
  },
  {
    id: "earth",
    name: "Earth",
    kind: "planet",
    group: "Solar System",
    diameterMiles: 7926,
    distanceFromSunMillionMiles: 93,
    meanSurfaceTempF: 59,
    moons: 1,
    ...contentImage("space", "earth", "The Earth seen from Apollo 17.jpg"),
    imageCredit: "NASA/Apollo 17 crew, Wikimedia Commons",
    fact: "Earth is our home planet and the only world known to have life.",
  },
  {
    id: "mercury",
    name: "Mercury",
    kind: "planet",
    group: "Solar System",
    diameterMiles: 3032,
    distanceFromSunMillionMiles: 36,
    meanSurfaceTempF: 333,
    moons: 0,
    ...contentImage("space", "mercury", "Mercury in true color.jpg"),
    imageCredit: "NASA/Johns Hopkins University Applied Physics Laboratory/Carnegie Institution of Washington",
    fact: "Mercury is closest to the Sun, but Venus is hotter because Mercury has almost no atmosphere.",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    kind: "planet",
    group: "Solar System",
    diameterMiles: 86881,
    distanceFromSunMillionMiles: 484,
    meanSurfaceTempF: -166,
    moons: 101,
    ...contentImage("space", "jupiter", "Jupiter and its shrunken Great Red Spot.jpg"),
    imageCredit: "NASA/ESA/A. Simon/M. H. Wong",
    fact: "Jupiter is the biggest planet in our solar system and has a giant storm called the Great Red Spot.",
  },
  {
    id: "saturn",
    name: "Saturn",
    kind: "planet",
    group: "Solar System",
    diameterMiles: 74898,
    distanceFromSunMillionMiles: 889,
    meanSurfaceTempF: -220,
    moons: 285,
    ...contentImage("space", "saturn", "Saturn during Equinox.jpg"),
    imageCredit: "NASA/JPL/Space Science Institute, Wikimedia Commons",
    imageFit: "contain",
    fact: "Saturn is famous for its bright ring system and now has the most confirmed moons of any planet.",
  },
  {
    id: "uranus",
    name: "Uranus",
    kind: "planet",
    group: "Solar System",
    diameterMiles: 31763,
    distanceFromSunMillionMiles: 1784,
    meanSurfaceTempF: -320,
    moons: 29,
    ...contentImage("space", "uranus", "Uranus2.jpg"),
    imageCredit: "NASA/JPL, Wikimedia Commons",
    fact: "Uranus is an ice giant that spins on its side as it travels around the Sun.",
  },
  {
    id: "neptune",
    name: "Neptune",
    kind: "planet",
    group: "Solar System",
    diameterMiles: 30599,
    distanceFromSunMillionMiles: 2781,
    meanSurfaceTempF: -330,
    moons: 16,
    ...contentImage("space", "neptune", "Neptune Full.jpg"),
    imageCredit: "NASA/JPL, Wikimedia Commons",
    fact: "Neptune is an ice giant with supersonic winds and a deep blue color.",
  },
  {
    id: "pluto",
    name: "Pluto",
    kind: "dwarf planet",
    group: "Dwarf Planets",
    diameterMiles: 1477,
    distanceFromSunMillionMiles: 3670,
    meanSurfaceTempF: -375,
    moons: 5,
    ...contentImage("space", "pluto", "Pluto in True Color - High-Res.jpg"),
    imageCredit: "NASA/JHUAPL/SwRI, Wikimedia Commons",
    fact: "Pluto is a dwarf planet in the Kuiper Belt with a heart-shaped icy plain.",
  },
  {
    id: "ceres",
    name: "Ceres",
    kind: "dwarf planet",
    group: "Dwarf Planets",
    diameterMiles: 588,
    distanceFromSunMillionMiles: 257,
    meanSurfaceTempF: -100,
    moons: 0,
    ...contentImage("space", "ceres", "Ceres - RC3 - Haulani Crater (22381131691).jpg"),
    imageCredit: "NASA/JPL-Caltech/UCLA/MPS/DLR/IDA, Wikimedia Commons",
    fact: "Ceres is the largest object in the asteroid belt between Mars and Jupiter.",
  },
  {
    id: "eris",
    name: "Eris",
    kind: "dwarf planet",
    group: "Dwarf Planets",
    diameterMiles: 1445,
    distanceFromSunMillionMiles: 6300,
    meanSurfaceTempF: -405,
    moons: 1,
    ...contentImage("space", "eris", "Eris and dysnomia2.jpg"),
    imageCredit: "NASA/ESA/M. Brown, Wikimedia Commons",
    fact: "Eris is a distant dwarf planet whose discovery helped change Pluto's classification.",
  },
  {
    id: "haumea",
    name: "Haumea",
    kind: "dwarf planet",
    group: "Dwarf Planets",
    diameterMiles: 1014,
    distanceFromSunMillionMiles: 4010,
    meanSurfaceTempF: -400,
    moons: 2,
    ...contentImage("space", "haumea", "Haumea Hubble.png"),
    imageCredit: "NASA/ESA/M. Brown, Wikimedia Commons",
    fact: "Haumea spins so fast that it is stretched into an oval shape.",
  },
  {
    id: "makemake",
    name: "Makemake",
    kind: "dwarf planet",
    group: "Dwarf Planets",
    diameterMiles: 888,
    distanceFromSunMillionMiles: 4260,
    meanSurfaceTempF: -405,
    moons: 1,
    ...contentImage("space", "makemake", "Makemake and its moon.jpg"),
    imageCredit: "NASA/ESA/A. Parker/M. Buie/W. Grundy, Wikimedia Commons",
    fact: "Makemake is a reddish dwarf planet in the Kuiper Belt.",
  },
  {
    id: "moon",
    name: "Moon",
    kind: "moon",
    group: "Earth's Moon",
    diameterMiles: 2159,
    distanceFromSunMillionMiles: 93,
    meanSurfaceTempF: -4,
    ...contentImage("space", "moon", "FullMoon2010.jpg"),
    imageCredit: "Gregory H. Revera, Wikimedia Commons",
    fact: "The Moon is Earth's only natural satellite and drives ocean tides.",
  },
  {
    id: "io",
    name: "Io",
    kind: "moon",
    group: "Jupiter Moons",
    diameterMiles: 2264,
    distanceFromSunMillionMiles: 484,
    meanSurfaceTempF: -202,
    ...contentImage("space", "io", "Io highest resolution true color.jpg"),
    imageCredit: "NASA/JPL/University of Arizona, Wikimedia Commons",
    fact: "Io is the most volcanically active world in the solar system.",
  },
  {
    id: "europa",
    name: "Europa",
    kind: "moon",
    group: "Jupiter Moons",
    diameterMiles: 1940,
    distanceFromSunMillionMiles: 484,
    meanSurfaceTempF: -260,
    ...contentImage("space", "europa", "Europa-moon.jpg"),
    imageCredit: "NASA/JPL/DLR, Wikimedia Commons",
    fact: "Europa has an icy crust and likely a salty ocean beneath it.",
  },
  {
    id: "ganymede",
    name: "Ganymede",
    kind: "moon",
    group: "Jupiter Moons",
    diameterMiles: 3273,
    distanceFromSunMillionMiles: 484,
    meanSurfaceTempF: -260,
    ...contentImage("space", "ganymede", "Ganymede g1 true-edit1.jpg"),
    imageCredit: "NASA/JPL, Wikimedia Commons",
    fact: "Ganymede is the largest moon in the solar system, bigger than Mercury.",
  },
  {
    id: "callisto",
    name: "Callisto",
    kind: "moon",
    group: "Jupiter Moons",
    diameterMiles: 2995,
    distanceFromSunMillionMiles: 484,
    meanSurfaceTempF: -218,
    ...contentImage("space", "callisto", "Callisto.jpg"),
    imageCredit: "NASA/JPL/DLR, Wikimedia Commons",
    fact: "Callisto is covered with ancient impact craters.",
  },
  {
    id: "titan",
    name: "Titan",
    kind: "moon",
    group: "Saturn Moons",
    diameterMiles: 3200,
    distanceFromSunMillionMiles: 889,
    meanSurfaceTempF: -290,
    ...contentImage("space", "titan", "Titan in true color.jpg"),
    imageCredit: "NASA/JPL/Space Science Institute, Wikimedia Commons",
    fact: "Titan has a thick atmosphere and lakes of liquid methane and ethane.",
  },
  {
    id: "enceladus",
    name: "Enceladus",
    kind: "moon",
    group: "Saturn Moons",
    diameterMiles: 313,
    distanceFromSunMillionMiles: 889,
    meanSurfaceTempF: -330,
    ...contentImage("space", "enceladus", "Enceladus from Voyager.jpg"),
    imageCredit: "NASA/JPL, Wikimedia Commons",
    fact: "Enceladus sprays icy plumes from a hidden ocean beneath its crust.",
  },
  {
    id: "mimas",
    name: "Mimas",
    kind: "moon",
    group: "Saturn Moons",
    diameterMiles: 246,
    distanceFromSunMillionMiles: 889,
    meanSurfaceTempF: -310,
    ...contentImage("space", "mimas", "Mimas Cassini.jpg"),
    imageCredit: "NASA/JPL/Space Science Institute, Wikimedia Commons",
    fact: "Mimas has a giant crater that makes it look like a space station.",
  },
  {
    id: "iapetus",
    name: "Iapetus",
    kind: "moon",
    group: "Saturn Moons",
    diameterMiles: 914,
    distanceFromSunMillionMiles: 889,
    meanSurfaceTempF: -285,
    ...contentImage("space", "iapetus", "Iapetus as seen by the Cassini probe - 20071008.jpg"),
    imageCredit: "NASA/JPL/Space Science Institute, Wikimedia Commons",
    fact: "Iapetus has one bright side, one dark side, and a huge ridge around its middle.",
  },
  {
    id: "rhea",
    name: "Rhea",
    kind: "moon",
    group: "Saturn Moons",
    diameterMiles: 949,
    distanceFromSunMillionMiles: 889,
    meanSurfaceTempF: -281,
    ...contentImage("space", "rhea", "Rhea moon.jpg"),
    imageCredit: "NASA/JPL/Space Science Institute, Wikimedia Commons",
    fact: "Rhea is Saturn's second-largest moon and is heavily cratered.",
  },
  {
    id: "dione",
    name: "Dione",
    kind: "moon",
    group: "Saturn Moons",
    diameterMiles: 698,
    distanceFromSunMillionMiles: 889,
    meanSurfaceTempF: -304,
    ...contentImage("space", "dione", "Dione3 cassini.jpg"),
    imageCredit: "NASA/JPL/Space Science Institute, Wikimedia Commons",
    fact: "Dione has bright icy cliffs and wispy streaks across its surface.",
  },
  {
    id: "tethys",
    name: "Tethys",
    kind: "moon",
    group: "Saturn Moons",
    diameterMiles: 662,
    distanceFromSunMillionMiles: 889,
    meanSurfaceTempF: -305,
    ...contentImage("space", "tethys", "Tethys PIA07738.jpg"),
    imageCredit: "NASA/JPL/Space Science Institute, Wikimedia Commons",
    fact: "Tethys has a huge canyon system called Ithaca Chasma.",
  },
  {
    id: "triton",
    name: "Triton",
    kind: "moon",
    group: "Neptune Moons",
    diameterMiles: 1680,
    distanceFromSunMillionMiles: 2781,
    meanSurfaceTempF: -391,
    ...contentImage("space", "triton", "Triton moon mosaic Voyager 2 (large).jpg"),
    imageCredit: "NASA/JPL/USGS, Wikimedia Commons",
    fact: "Triton orbits Neptune backward and has extremely cold nitrogen ice.",
  },
  {
    id: "charon",
    name: "Charon",
    kind: "moon",
    group: "Pluto Moons",
    diameterMiles: 753,
    distanceFromSunMillionMiles: 3670,
    meanSurfaceTempF: -369,
    ...contentImage("space", "charon", "Charon in True Color - High-Res.jpg"),
    imageCredit: "NASA/JHUAPL/SwRI, Wikimedia Commons",
    fact: "Charon is so large compared with Pluto that the two worlds orbit a point between them.",
  },
  {
    id: "phobos",
    name: "Phobos",
    kind: "moon",
    group: "Mars Moons",
    diameterMiles: 14,
    distanceFromSunMillionMiles: 142,
    meanSurfaceTempF: -40,
    ...contentImage("space", "phobos", "Phobos colour 2008.jpg"),
    imageCredit: "NASA/JPL-Caltech/University of Arizona, Wikimedia Commons",
    fact: "Phobos is the larger moon of Mars and is slowly spiraling inward.",
  },
  {
    id: "deimos",
    name: "Deimos",
    kind: "moon",
    group: "Mars Moons",
    diameterMiles: 8,
    distanceFromSunMillionMiles: 142,
    meanSurfaceTempF: -40,
    ...contentImage("space", "deimos", "Deimos-MRO.jpg"),
    imageCredit: "NASA/JPL-Caltech/University of Arizona, Wikimedia Commons",
    fact: "Deimos is the smaller, outer moon of Mars.",
  },
  {
    id: "miranda",
    name: "Miranda",
    kind: "moon",
    group: "Uranus Moons",
    diameterMiles: 293,
    distanceFromSunMillionMiles: 1784,
    meanSurfaceTempF: -335,
    ...contentImage("space", "miranda", "Miranda.jpg"),
    imageCredit: "NASA/JPL, Wikimedia Commons",
    fact: "Miranda has strange patchwork terrain with cliffs and grooves.",
  },
  {
    id: "ariel",
    name: "Ariel",
    kind: "moon",
    group: "Uranus Moons",
    diameterMiles: 720,
    distanceFromSunMillionMiles: 1784,
    meanSurfaceTempF: -351,
    ...contentImage("space", "ariel", "Ariel (moon).jpg"),
    imageCredit: "NASA/JPL, Wikimedia Commons",
    fact: "Ariel is one of Uranus's brighter moons and has canyons across its icy surface.",
  },
  {
    id: "titania",
    name: "Titania",
    kind: "moon",
    group: "Uranus Moons",
    diameterMiles: 981,
    distanceFromSunMillionMiles: 1784,
    meanSurfaceTempF: -334,
    ...contentImage("space", "titania", "Titania (moon).jpg"),
    imageCredit: "NASA/JPL, Wikimedia Commons",
    fact: "Titania is the largest moon of Uranus.",
  },
  {
    id: "oberon",
    name: "Oberon",
    kind: "moon",
    group: "Uranus Moons",
    diameterMiles: 946,
    distanceFromSunMillionMiles: 1784,
    meanSurfaceTempF: -334,
    ...contentImage("space", "oberon", "Oberon (moon).jpg"),
    imageCredit: "NASA/JPL, Wikimedia Commons",
    fact: "Oberon is a dark, cratered moon of Uranus.",
  },
  {
    id: "vy-canis-majoris",
    name: "VY Canis Majoris",
    kind: "star",
    group: "Huge Stars",
    surfaceTempK: 3490,
    radiusSolar: 1420,
    distanceLightYears: 3900,
    ...contentImage("space", "vy-canis-majoris", "Sun and VY Canis Majoris.svg"),
    imageCredit: "Wikimedia Commons scale illustration",
    statNote: "Estimated radius; huge stars are difficult to measure exactly.",
    fact: "VY Canis Majoris is a red hypergiant. It is far larger than the Sun, but its exact size is hard to measure.",
  },
  {
    id: "stephenson-2-18",
    name: "Stephenson 2-18",
    kind: "star",
    group: "Huge Stars",
    surfaceTempK: 3200,
    radiusSolar: 2150,
    distanceLightYears: 19000,
    ...contentImage("space", "stephenson-2-18", "Artist’s impression of the red supergiant star Antares.jpg"),
    imageCredit: "ESO/M. Kornmesser, Wikimedia Commons",
    statNote: "Estimated radius; scientists revise giant-star measurements.",
    fact: "Stephenson 2-18 is a red supergiant and one of the largest star candidates by estimated radius.",
  },
  {
    id: "rigel",
    name: "Rigel",
    kind: "star",
    group: "Hot Stars",
    surfaceTempK: 12100,
    radiusSolar: 79,
    distanceLightYears: 860,
    ...contentImage("space", "rigel", "Rigel and IC 2118 - The Witch Head Nebula - Flickr - gjdonatiello.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Rigel is a blue supergiant. Blue stars are much hotter at the surface than red stars.",
  },
  {
    id: "betelgeuse",
    name: "Betelgeuse",
    kind: "star",
    group: "Huge Stars",
    surfaceTempK: 3500,
    radiusSolar: 760,
    distanceLightYears: 550,
    ...contentImage("space", "betelgeuse", "ESO-Betelgeuse.jpg"),
    imageCredit: "ESO/P. Kervella, Wikimedia Commons",
    fact: "Betelgeuse is a red supergiant in Orion. It is huge, but its surface is cooler than blue stars.",
  },
  {
    id: "sirius",
    name: "Sirius",
    kind: "star",
    group: "Bright Stars",
    surfaceTempK: 9940,
    radiusSolar: 1.7,
    distanceLightYears: 8.6,
    ...contentImage("space", "sirius", "Sirius A and B artwork.jpg"),
    imageCredit: "NASA/ESA/G. Bacon, Wikimedia Commons",
    fact: "Sirius is the brightest star in Earth's night sky and is much closer than most stars we see.",
  },
  {
    id: "proxima-centauri",
    name: "Proxima Centauri",
    kind: "star",
    group: "Nearby Stars",
    surfaceTempK: 3040,
    radiusSolar: 0.15,
    distanceLightYears: 4.25,
    ...contentImage("space", "proxima-centauri", "Proxima Centauri by Hubble Space Telescope 2013.jpg"),
    imageCredit: "ESA/Hubble & NASA, Wikimedia Commons",
    fact: "Proxima Centauri is the closest known star to the Sun.",
  },
  {
    id: "vega",
    name: "Vega",
    kind: "star",
    group: "Bright Stars",
    surfaceTempK: 9600,
    radiusSolar: 2.4,
    distanceLightYears: 25,
    ...contentImage("space", "vega", "Vega.jpg"),
    imageCredit: "Stephen Rahn, Wikimedia Commons",
    fact: "Vega is a bright blue-white star in the constellation Lyra.",
  },
  {
    id: "polaris",
    name: "Polaris",
    kind: "star",
    group: "Bright Stars",
    surfaceTempK: 6000,
    radiusSolar: 37,
    distanceLightYears: 448,
    ...contentImage("space", "polaris", "Polaris star.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Polaris is famous as the North Star because it sits near Earth's north celestial pole.",
  },
  {
    id: "antares",
    name: "Antares",
    kind: "star",
    group: "Huge Stars",
    surfaceTempK: 3600,
    radiusSolar: 680,
    distanceLightYears: 550,
    ...contentImage("space", "antares", "Antares star.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "Antares is a red supergiant star and the bright heart of Scorpius.",
  },
  {
    id: "andromeda-galaxy",
    name: "Andromeda Galaxy",
    kind: "region",
    group: "Galaxies",
    distanceLightYears: 2537000,
    ...contentImage("space", "andromeda-galaxy", "Andromeda Galaxy (with h-alpha).jpg"),
    imageCredit: "Adam Evans, Wikimedia Commons",
    imageFit: "contain",
    fact: "Andromeda is the nearest large spiral galaxy to the Milky Way.",
  },
  {
    id: "milky-way",
    name: "Milky Way",
    kind: "region",
    group: "Galaxies",
    ...contentImage("space", "milky-way", "Milky Way Arch.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "The Milky Way is our home galaxy, a vast spiral of stars, gas, and dust.",
  },
  {
    id: "asteroid-belt",
    name: "Asteroid Belt",
    kind: "region",
    group: "Solar System Regions",
    distanceFromSunMillionMiles: 257,
    ...contentImage("space", "asteroid-belt", "Asteroid Belt.jpg"),
    imageCredit: "Wikimedia Commons",
    fact: "The asteroid belt is a region of rocky objects between Mars and Jupiter.",
  },
  {
    id: "kuiper-belt",
    name: "Kuiper Belt",
    kind: "region",
    group: "Solar System Regions",
    distanceFromSunMillionMiles: 4400,
    ...contentImage("space", "kuiper-belt", "Kuiper belt plot objects of outer solar system.png"),
    imageCredit: "WilyD, Wikimedia Commons",
    imageFit: "contain",
    fact: "The Kuiper Belt is a distant region of icy worlds beyond Neptune.",
  },
  {
    id: "oort-cloud",
    name: "Oort Cloud",
    kind: "region",
    group: "Solar System Regions",
    distanceFromSunMillionMiles: 930000,
    ...contentImage("space", "oort-cloud", "Oort cloud Sedna orbit.svg"),
    imageCredit: "NASA/Wikimedia Commons",
    imageFit: "contain",
    statNote: "Distance is a broad inner-edge estimate; the Oort Cloud is enormous.",
    fact: "The Oort Cloud is a faraway shell of icy objects that may send comets inward.",
  },
  {
    id: "black-hole",
    name: "Black Hole",
    kind: "concept",
    group: "Cosmic Ideas",
    ...contentImage("space", "black-hole", "Black hole - Messier 87.jpg"),
    imageCredit: "Event Horizon Telescope Collaboration",
    fact: "A black hole is a place where gravity is so strong that light cannot escape once it gets too close.",
    conceptQuestion: "What is a black hole?",
    conceptAnswer: "A place in space where gravity is so strong that even light cannot escape.",
  },
  {
    id: "supernova",
    name: "Supernova",
    kind: "concept",
    group: "Cosmic Ideas",
    ...contentImage("space", "supernova", "Crab Nebula.jpg"),
    imageCredit: "NASA/ESA/J. Hester/A. Loll",
    fact: "A supernova is an extremely bright, powerful explosion of a star.",
    conceptQuestion: "What is a supernova?",
    conceptAnswer: "A super-powerful star explosion that blasts material into space.",
  },
  {
    id: "nebula",
    name: "Nebula",
    kind: "concept",
    group: "Cosmic Ideas",
    ...contentImage("space", "nebula", "Pillars of Creation (NIRCam Image).jpg"),
    imageCredit: "NASA/ESA/CSA/STScI",
    fact: "A nebula is a giant cloud of gas and dust. Some nebulae are places where stars are born.",
    conceptQuestion: "Where can a star be born?",
    conceptAnswer: "Inside a nebula, where gravity pulls gas and dust together.",
  },
];

export const jets: Jet[] = [
  { id: "f-35-lightning-ii", name: "F-35 Lightning II", country: "United States", category: "stealth", maxSpeedMph: 1200, rangeMiles: 1380, firepower: 5, ...contentImage("jets", "f-35-lightning-ii", "F-35A flight (cropped).jpg"), imageCredit: "U.S. Air Force/Wikimedia Commons", fact: "The F-35 is a stealth multirole fighter with sensors that help it spot threats before they spot it." },
  { id: "f-22-raptor", name: "F-22 Raptor", country: "United States", category: "stealth", maxSpeedMph: 1500, rangeMiles: 1840, firepower: 5, ...contentImage("jets", "f-22-raptor", "F-22 Raptor edit1 (cropped).jpg"), imageCredit: "U.S. Air Force/Wikimedia Commons", fact: "The F-22 was built for air superiority: stealth, supercruise speed, and extreme agility." },
  { id: "su-57", name: "Sukhoi Su-57", country: "Russia", category: "stealth", maxSpeedMph: 1320, rangeMiles: 2200, firepower: 5, ...contentImage("jets", "su-57", "Sukhoi Design Bureau, 054, Sukhoi T-50 (Su-57 prototype) (49581303977).jpg"), imageCredit: "Dmitry Terekhov/Wikimedia Commons", fact: "The Su-57 is Russia's stealth fighter design, mixing internal weapons bays with high maneuverability." },
  { id: "j-20", name: "Chengdu J-20", country: "China", category: "stealth", maxSpeedMph: 1300, rangeMiles: 2100, firepower: 5, ...contentImage("jets", "j-20", "J-20 at CCAS2022 (20220827103424).jpg"), imageCredit: "N509FZ/Wikimedia Commons", fact: "The J-20 is a large stealth fighter designed for long-range missions and beyond-visual-range combat." },
  { id: "b-2-spirit", name: "B-2 Spirit", country: "United States", category: "bomber", maxSpeedMph: 630, rangeMiles: 6900, firepower: 5, ...contentImage("jets", "b-2-spirit", "RAF F-35B integration flying training with USAF B-2 30092019 - 4.jpg"), imageCredit: "Royal Air Force/Wikimedia Commons", imagePosition: "center 40%", fact: "The B-2 is a stealth bomber with a flying-wing shape and intercontinental range." },
  { id: "b-21-raider", name: "B-21 Raider", country: "United States", category: "bomber", maxSpeedMph: 620, rangeMiles: 6000, firepower: 5, ...contentImage("jets", "b-21-raider", "B-21-in-flight.jpg"), imageCredit: "U.S. Air Force/Wikimedia Commons", fact: "The B-21 Raider is a newer stealth bomber designed to fly deep into defended airspace." },
  { id: "f-117-nighthawk", name: "F-117 Nighthawk", country: "United States", category: "stealth", maxSpeedMph: 684, rangeMiles: 1070, firepower: 3, ...contentImage("jets", "f-117-nighthawk", "F-117 Nighthawk Front.jpg"), imageCredit: "U.S. Air Force/Wikimedia Commons", fact: "The F-117 was an early operational stealth attack jet with sharp radar-deflecting angles." },
  { id: "sr-71-blackbird", name: "SR-71 Blackbird", country: "United States", category: "recon", maxSpeedMph: 2200, rangeMiles: 3200, firepower: 1, ...contentImage("jets", "sr-71-blackbird", "Lockheed SR-71 Blackbird.jpg"), imageCredit: "NASA/Wikimedia Commons", fact: "The SR-71 was a spy plane so fast it could outrun many threats instead of fighting them." },
  { id: "u-2", name: "Lockheed U-2", country: "United States", category: "recon", maxSpeedMph: 500, rangeMiles: 7000, firepower: 1, ...contentImage("jets", "u-2", "Usaf.u2.750pix.jpg"), imageCredit: "U.S. Air Force/Wikimedia Commons", fact: "The U-2 is a high-altitude reconnaissance jet that can fly above 70,000 feet." },
  { id: "f-15-eagle", name: "F-15 Eagle", country: "United States", category: "dogfighter", maxSpeedMph: 1650, rangeMiles: 3000, firepower: 5, ...contentImage("jets", "f-15-eagle", "F-15C Eagle from the 44th Fighter Squadron flies during a routine training exercise April 15, 2019.jpg"), imageCredit: "U.S. Air Force/Wikimedia Commons", fact: "The F-15 Eagle is a powerful air-superiority fighter famous for speed, climb, and missile load." },
  { id: "f-a-18-hornet", name: "F/A-18 Hornet", country: "United States", category: "multirole", maxSpeedMph: 1190, rangeMiles: 1250, firepower: 4, ...contentImage("jets", "f-a-18-hornet", "FA-18C desert refueling.jpg"), imageCredit: "U.S. Navy/Wikimedia Commons", fact: "The Hornet can fly from carriers and switch between fighter and attack missions." },
  { id: "f-a-18-super-hornet", name: "F/A-18E/F Super Hornet", country: "United States", category: "multirole", maxSpeedMph: 1190, rangeMiles: 1460, firepower: 4, ...contentImage("jets", "f-a-18-super-hornet", "US Navy 071203-N-8923M-074 An F-A-18F Super Hornet, from the Red Rippers of Strike Fighter Squadron (VFA) 11, makes a sharp turn above the flight deck aboard the Nimitz-class nuclear-powered aircraft carrier USS Harry S. Truman.jpg"), imageCredit: "U.S. Navy/Wikimedia Commons", fact: "The Super Hornet is a bigger carrier fighter than the original Hornet and can carry a wide mix of weapons." },
  { id: "f-16-fighting-falcon", name: "F-16 Fighting Falcon", country: "United States", category: "multirole", maxSpeedMph: 1320, rangeMiles: 2620, firepower: 4, ...contentImage("jets", "f-16-fighting-falcon", "F-16 June 2008.jpg"), imageCredit: "U.S. Air Force/Wikimedia Commons", fact: "The F-16 is a lightweight fighter with a bubble canopy and excellent turning performance." },
  { id: "f-14-tomcat", name: "F-14 Tomcat", country: "United States", category: "interceptor", maxSpeedMph: 1544, rangeMiles: 1840, firepower: 5, ...contentImage("jets", "f-14-tomcat", "US Navy 051105-F-5480T-005 An F-14D Tomcat conducts a mission over the Persian Gulf-region.jpg"), imageCredit: "U.S. Navy/Wikimedia Commons", fact: "The F-14 used swing wings and long-range missiles to defend aircraft carriers." },
  { id: "a-10-thunderbolt-ii", name: "A-10 Thunderbolt II", country: "United States", category: "attack", maxSpeedMph: 420, rangeMiles: 2580, firepower: 4, ...contentImage("jets", "a-10-thunderbolt-ii", "Fairchild Republic A-10 Thunderbolt II - 32156159151.jpg"), imageCredit: "Alan Wilson/Wikimedia Commons", fact: "The A-10 is built around a huge 30 mm cannon for close air support." },
  { id: "rafale", name: "Dassault Rafale", country: "France", category: "multirole", maxSpeedMph: 1190, rangeMiles: 2300, firepower: 5, ...contentImage("jets", "rafale", "Rafale - RIAT 2009 (3751416421).jpg"), imageCredit: "Tim Felce/Wikimedia Commons", fact: "The Rafale is a French multirole fighter used for air combat, strike, and carrier missions." },
  { id: "eurofighter-typhoon", name: "Eurofighter Typhoon", country: "United Kingdom/Germany/Italy/Spain", category: "dogfighter", maxSpeedMph: 1550, rangeMiles: 1800, firepower: 5, ...contentImage("jets", "eurofighter-typhoon", "RAF Eurofighter EF-2000 Typhoon F2 Lofting-1.jpg"), imageCredit: "Kogo/Wikimedia Commons", fact: "The Typhoon is a fast delta-canard fighter known for sharp air-to-air performance." },
  { id: "jas-39-gripen", name: "Saab JAS 39 Gripen", country: "Sweden", category: "multirole", maxSpeedMph: 1530, rangeMiles: 2000, firepower: 4, ...contentImage("jets", "jas-39-gripen", "Saab JAS 39 Gripen at Kaivopuisto Air Show, June 2017 (altered) copy.jpg"), imageCredit: "Jakub Halun/Wikimedia Commons", fact: "The Gripen is designed to operate from short roads and be maintained quickly between missions." },
  { id: "mig-29", name: "Mikoyan MiG-29", country: "Russia", category: "dogfighter", maxSpeedMph: 1520, rangeMiles: 890, firepower: 4, ...contentImage("jets", "mig-29", "VVS 100th IMG 0691 (7727464290) (cropped).jpg"), imageCredit: "Dmitry Terekhov/Wikimedia Commons", fact: "The MiG-29 is a nimble fighter built for short-range air combat and quick interception." },
  { id: "su-27", name: "Sukhoi Su-27", country: "Russia", category: "dogfighter", maxSpeedMph: 1550, rangeMiles: 2200, firepower: 5, ...contentImage("jets", "su-27", "Sukhoi Su-27SKM at MAKS-2005 airshow.jpg"), imageCredit: "Alex Beltyukov/Wikimedia Commons", fact: "The Su-27 is a large, agile fighter that inspired many later Flanker-family jets." },
  { id: "su-35", name: "Sukhoi Su-35", country: "Russia", category: "dogfighter", maxSpeedMph: 1490, rangeMiles: 2200, firepower: 5, ...contentImage("jets", "su-35", "Russian Air Force, RF-81719, Sukhoi Su-35S (49581740157).jpg"), imageCredit: "Dmitry Terekhov/Wikimedia Commons", fact: "The Su-35 adds thrust-vectoring engines and modern sensors to the Flanker family." },
  { id: "su-34", name: "Sukhoi Su-34", country: "Russia", category: "attack", maxSpeedMph: 1180, rangeMiles: 2500, firepower: 5, ...contentImage("jets", "su-34", "MAKS2015part1-10 (cropped).jpg"), imageCredit: "Alex Beltyukov/Wikimedia Commons", fact: "The Su-34 is a strike aircraft with side-by-side seats and long-range attack capability." },
  { id: "mig-31", name: "Mikoyan MiG-31", country: "Russia", category: "interceptor", maxSpeedMph: 1860, rangeMiles: 1900, firepower: 5, ...contentImage("jets", "mig-31", "Russian Air Force Mikoyan-Gurevich MiG-31P.jpg"), imageCredit: "Dmitry Pichugin/Wikimedia Commons", fact: "The MiG-31 is a very fast interceptor built to cover huge distances quickly." },
  { id: "tu-160", name: "Tupolev Tu-160", country: "Russia", category: "bomber", maxSpeedMph: 1379, rangeMiles: 7600, firepower: 5, ...contentImage("jets", "tu-160", "Tupolev Tu-160 RF-94109.jpg"), imageCredit: "Dmitry Terekhov/Wikimedia Commons", fact: "The Tu-160 is a supersonic strategic bomber with swing wings and enormous range." },
  { id: "tu-22m", name: "Tupolev Tu-22M", country: "Russia", category: "bomber", maxSpeedMph: 1240, rangeMiles: 3100, firepower: 5, ...contentImage("jets", "tu-22m", "Tupolev Tu-22M3M GEFEST (19230388334).jpg"), imageCredit: "Dmitry Terekhov/Wikimedia Commons", fact: "The Tu-22M is a fast bomber designed for long-range strike missions." },
  { id: "b-1-lancer", name: "B-1 Lancer", country: "United States", category: "bomber", maxSpeedMph: 830, rangeMiles: 5900, firepower: 5, ...contentImage("jets", "b-1-lancer", "B-1B air refueling.jpg"), imageCredit: "U.S. Air Force/Wikimedia Commons", fact: "The B-1 Lancer is a swing-wing bomber that can carry a very large conventional payload." },
  { id: "b-52-stratofortress", name: "B-52 Stratofortress", country: "United States", category: "bomber", maxSpeedMph: 650, rangeMiles: 8800, firepower: 5, ...contentImage("jets", "b-52-stratofortress", "B-52 Stratofortress assigned to the 307th Bomb Wing (cropped).jpg"), imageCredit: "U.S. Air Force/Wikimedia Commons", fact: "The B-52 has served for decades because it can fly far and carry a heavy weapons load." },
  { id: "mirage-2000", name: "Dassault Mirage 2000", country: "France", category: "multirole", maxSpeedMph: 1450, rangeMiles: 960, firepower: 4, ...contentImage("jets", "mirage-2000", "Mirage 2000C in-flight 2 (cropped).jpg"), imageCredit: "French Air and Space Force/Wikimedia Commons", fact: "The Mirage 2000 is a delta-wing fighter known for speed and clean, sharp handling." },
  { id: "mirage-f1", name: "Dassault Mirage F1", country: "France", category: "interceptor", maxSpeedMph: 1450, rangeMiles: 2050, firepower: 4, ...contentImage("jets", "mirage-f1", "Mirage F1C (26701300084).jpg"), imageCredit: "Rob Schleiffert/Wikimedia Commons", fact: "The Mirage F1 used a swept wing instead of the Mirage 2000's delta wing and served with many air forces." },
  { id: "sepecat-jaguar", name: "SEPECAT Jaguar", country: "United Kingdom/France", category: "attack", maxSpeedMph: 1050, rangeMiles: 2190, firepower: 4, ...contentImage("jets", "sepecat-jaguar", "French Jaguar A of EC 1-7 Provence in flight over the Adriatic Sea, 8 April 2003 (DF-SD-05-05511).jpg"), imageCredit: "U.S. Navy/Wikimedia Commons", fact: "The Jaguar was a low-level attack jet built by Britain and France." },
  { id: "panavia-tornado", name: "Panavia Tornado", country: "United Kingdom/Germany/Italy", category: "attack", maxSpeedMph: 1490, rangeMiles: 2400, firepower: 5, ...contentImage("jets", "panavia-tornado", "RAF Tornado GR4 MOD 45155233.jpg"), imageCredit: "UK Ministry of Defence/Wikimedia Commons", fact: "The Tornado used swing wings for fast low-level strike missions." },
  { id: "av-8b-harrier-ii", name: "AV-8B Harrier II", country: "United States/United Kingdom", category: "attack", maxSpeedMph: 673, rangeMiles: 1400, firepower: 4, ...contentImage("jets", "av-8b-harrier-ii", "Boeing AV-8B Harrier II, Italy - Navy JP7306232.jpg"), imageCredit: "Alan Wilson/Wikimedia Commons", fact: "The AV-8B Harrier II can take off from short decks and land vertically like a jump jet." },
  { id: "hawker-harrier", name: "Hawker Siddeley Harrier", country: "United Kingdom", category: "attack", maxSpeedMph: 730, rangeMiles: 1150, firepower: 3, ...contentImage("jets", "hawker-harrier", "Hawker Siddeley Harrier (35066585575).jpg"), imageCredit: "Timo Newton-Syms/Wikimedia Commons", fact: "The original Harrier made vertical and short takeoff combat jets famous." },
  { id: "l-39-albatros", name: "Aero L-39 Albatros", country: "Czechoslovakia", category: "trainer", maxSpeedMph: 470, rangeMiles: 680, firepower: 2, ...contentImage("jets", "l-39-albatros", "L-39ZA Albatros (cropped).jpg"), imageCredit: "Alan Wilson/Wikimedia Commons", fact: "The L-39 is a popular jet trainer that also has light attack versions." },
  { id: "t-50-golden-eagle", name: "T-50 Golden Eagle", country: "South Korea", category: "trainer", maxSpeedMph: 1060, rangeMiles: 1150, firepower: 3, ...contentImage("jets", "t-50-golden-eagle", "Phillipine Air Force FA-50PH.jpg"), imageCredit: "Dmitry A. Mottl/Wikimedia Commons", fact: "The T-50 is a supersonic trainer, and its FA-50 version can fight as a light combat jet." },
  { id: "yak-130", name: "Yakovlev Yak-130", country: "Russia", category: "trainer", maxSpeedMph: 660, rangeMiles: 1300, firepower: 3, ...contentImage("jets", "yak-130", "Yakovlev Yak-130.jpg"), imageCredit: "Adrian Pingstone/Wikimedia Commons", fact: "The Yak-130 trains pilots for modern fighters and can carry light attack weapons." },
  { id: "hongdu-l-15", name: "Hongdu L-15", country: "China", category: "trainer", maxSpeedMph: 1050, rangeMiles: 1900, firepower: 3, ...contentImage("jets", "hongdu-l-15", "L15 (17810345710).jpg"), imageCredit: "Peng Chen/Wikimedia Commons", fact: "The Hongdu L-15 is an advanced jet trainer with a light combat role." },
  { id: "j-10", name: "Chengdu J-10", country: "China", category: "multirole", maxSpeedMph: 1450, rangeMiles: 2000, firepower: 4, ...contentImage("jets", "j-10", "J-10B with PL-10 and PL-12.jpg"), imageCredit: "Alert5/Wikimedia Commons", fact: "The J-10 is a single-engine Chinese multirole fighter with a delta-canard layout." },
  { id: "j-11", name: "Shenyang J-11", country: "China", category: "dogfighter", maxSpeedMph: 1550, rangeMiles: 2200, firepower: 4, ...contentImage("jets", "j-11", "Chinese-j-11.jpg"), imageCredit: "U.S. Navy/Wikimedia Commons", fact: "The J-11 is a Chinese Flanker-family fighter based on the Su-27 design." },
  { id: "j-16", name: "Shenyang J-16", country: "China", category: "multirole", maxSpeedMph: 1550, rangeMiles: 2400, firepower: 5, ...contentImage("jets", "j-16", "PLAAF J-16 - 2.jpg"), imageCredit: "N509FZ/Wikimedia Commons", fact: "The J-16 is a two-seat multirole fighter built for air-to-air and strike missions." },
  { id: "fc-31", name: "Shenyang FC-31", country: "China", category: "stealth", maxSpeedMph: 1360, rangeMiles: 1200, firepower: 4, ...contentImage("jets", "fc-31", "Shenyang J-31 (F60) at 2014 Zhuhai Air Show.jpg"), imageCredit: "N509FZ/Wikimedia Commons", fact: "The FC-31 is a Chinese stealth fighter prototype with twin engines and internal weapons bays." },
  { id: "hal-tejas", name: "HAL Tejas", country: "India", category: "multirole", maxSpeedMph: 1220, rangeMiles: 1150, firepower: 4, ...contentImage("jets", "hal-tejas", "HAL Tejas (LA-5018) of Squadron 18 Flying Bullets.jpg"), imageCredit: "Indian Air Force/Wikimedia Commons", fact: "The Tejas is India's lightweight multirole fighter with a compact delta-wing design." },
  { id: "mitsubishi-f-2", name: "Mitsubishi F-2", country: "Japan", category: "multirole", maxSpeedMph: 1320, rangeMiles: 2100, firepower: 4, ...contentImage("jets", "mitsubishi-f-2", "Mitsubishi F-2.jpg"), imageCredit: "Japan Air Self-Defense Force/Wikimedia Commons", fact: "The Mitsubishi F-2 is a Japanese fighter related to the F-16 but with a larger wing." },
  { id: "f-15j", name: "Mitsubishi F-15J", country: "Japan", category: "interceptor", maxSpeedMph: 1650, rangeMiles: 3000, firepower: 5, ...contentImage("jets", "f-15j", "JASDF equipment F-15J (7).jpg"), imageCredit: "Japan Air Self-Defense Force/Wikimedia Commons", fact: "The F-15J is Japan's version of the Eagle, used for fast air defense missions." },
  { id: "f-ck-1", name: "AIDC F-CK-1 Ching-kuo", country: "Taiwan", category: "multirole", maxSpeedMph: 790, rangeMiles: 680, firepower: 3, ...contentImage("jets", "f-ck-1", "AIDC F-CK-1 Ching-kuo (36754649465).jpg"), imageCredit: "ltdccba/Wikimedia Commons", fact: "The F-CK-1 Ching-kuo is a Taiwanese multirole fighter designed for island air defense." },
  { id: "iai-kfir", name: "IAI Kfir", country: "Israel", category: "multirole", maxSpeedMph: 1520, rangeMiles: 800, firepower: 4, ...contentImage("jets", "iai-kfir", "Colombian Air Force Kfir (cropped).jpg"), imageCredit: "Alex Beltyukov/Wikimedia Commons", fact: "The Kfir is an Israeli fighter derived from Mirage-style delta-wing designs." },
  { id: "f-5", name: "Northrop F-5", country: "United States", category: "dogfighter", maxSpeedMph: 1060, rangeMiles: 1540, firepower: 3, ...contentImage("jets", "f-5", "J-3005.jpg"), imageCredit: "Adrian Pingstone/Wikimedia Commons", fact: "The F-5 is a small, simple fighter used by many countries and often used for training opponents." },
  { id: "f-4-phantom-ii", name: "F-4 Phantom II", country: "United States", category: "multirole", maxSpeedMph: 1470, rangeMiles: 1700, firepower: 5, ...contentImage("jets", "f-4-phantom-ii", "QF-4 Holloman AFB.jpg"), imageCredit: "U.S. Air Force/Wikimedia Commons", fact: "The F-4 Phantom II was a big twin-engine fighter used for interception, attack, and reconnaissance." },
  { id: "english-electric-lightning", name: "English Electric Lightning", country: "United Kingdom", category: "interceptor", maxSpeedMph: 1500, rangeMiles: 850, firepower: 4, ...contentImage("jets", "english-electric-lightning", "English Electric Lightning F6, UK - Air Force AN2260192.jpg"), imageCredit: "Alan Wilson/Wikimedia Commons", fact: "The Lightning was a British interceptor famous for its incredible climb rate." },
  { id: "mig-21", name: "MiG-21", country: "Soviet Union", category: "interceptor", maxSpeedMph: 1350, rangeMiles: 750, firepower: 3, ...contentImage("jets", "mig-21", "Croatian MiG-21 (cropped).jpg"), imageCredit: "Christian Volpati/Wikimedia Commons", fact: "The MiG-21 is one of the most-produced supersonic jet fighters in history." },
];

export const topicIds = ["peppers", "buildings", "sharks", "space", "jets"] as const satisfies readonly KnowledgeTopic[];

export const topicPacks: Record<KnowledgeTopic, TopicPack> = {
  peppers: {
    id: "peppers",
    label: "Spicy Peppers",
    eyebrow: `${contentLibraryStats.peppers}+ peppers`,
    roundLabel: "Pepper round",
    libraryCount: contentLibraryStats.peppers,
    featuredCount: peppers.length,
    sources: [
      { label: "WikiPepper", url: "https://wikipepper.org/peppers" },
      { label: "PepperScale chile guides", url: "https://pepperscale.com/" },
    ],
    samples: ["Aji Charapita", "Datil", "Naga Viper", "Carolina Reaper"],
  },
  buildings: {
    id: "buildings",
    label: "Sky Scrapers",
    eyebrow: `${contentLibraryStats.buildings}+ towers`,
    roundLabel: "Tower round",
    libraryCount: contentLibraryStats.buildings,
    featuredCount: buildings.length,
    sources: [
      { label: "Wikidata skyscraper records", url: "https://query.wikidata.org/" },
      { label: "The Skyscraper Center", url: "https://www.skyscrapercenter.com/" },
    ],
    samples: ["Burj Khalifa", "Merdeka 118", "Shanghai Tower", "One World Trade Center"],
  },
  sharks: {
    id: "sharks",
    label: "Shark Tank",
    eyebrow: `${contentLibraryStats.sharks}+ sharks`,
    roundLabel: "Shark round",
    libraryCount: contentLibraryStats.sharks,
    featuredCount: sharks.length,
    sources: [
      { label: "Wikidata shark taxonomy", url: "https://query.wikidata.org/" },
      { label: "Florida Museum shark profiles", url: "https://www.floridamuseum.ufl.edu/discover-fish/sharks/" },
      { label: "Britannica placoderm notes", url: "https://www.britannica.com/animal/placoderm" },
    ],
    samples: ["Whale Shark", "Longfin Mako", "Angelshark", "Megalodon"],
  },
  space: {
    id: "space",
    label: "Space Universe",
    eyebrow: `${spaceCards.length} space cards`,
    roundLabel: "Space round",
    libraryCount: spaceCards.length,
    featuredCount: spaceCards.length,
    sources: [
      { label: "NASA Venus facts", url: "https://science.nasa.gov/venus/venus-facts" },
      { label: "NASA solar-system temperatures", url: "https://science.nasa.gov/solar-system/temperatures-across-our-solar-system/" },
      { label: "NASA planetary moon counts", url: "https://science.nasa.gov/solar-system/moons/" },
      { label: "IAU MPC moon confirmations", url: "https://www.iau.org/IAU/IAU/News/Ann2026/MPC-New-Moons-Saturn-Jupiter.aspx" },
      { label: "NASA Space Place", url: "https://spaceplace.nasa.gov/" },
    ],
    samples: ["Pluto", "Europa", "Saturn", "Andromeda Galaxy"],
  },
  jets: {
    id: "jets",
    label: "Jet Hangar",
    eyebrow: `${contentLibraryStats.jets}+ aircraft`,
    roundLabel: "Jet round",
    libraryCount: contentLibraryStats.jets,
    featuredCount: jets.length,
    sources: [
      { label: "Wikimedia aircraft media", url: "https://commons.wikimedia.org/wiki/Category:Military_aircraft" },
      { label: "Wikidata aircraft records", url: "https://query.wikidata.org/" },
    ],
    samples: ["F-22 Raptor", "SR-71 Blackbird", "Rafale", "MiG-31"],
  },
};

export const topicCatalog: Record<Exclude<TopicId, "mixed">, {
  label: string;
  eyebrow: string;
  roundLabel: string;
}> = Object.fromEntries(topicIds.map((id) => [id, {
  label: topicPacks[id].label,
  eyebrow: topicPacks[id].eyebrow,
  roundLabel: topicPacks[id].roundLabel,
}])) as Record<KnowledgeTopic, { label: string; eyebrow: string; roundLabel: string }>;

export const topicOptions: { id: TopicId; label: string; eyebrow: string }[] = [
  { id: "mixed", label: "Mix it up", eyebrow: "All labs" },
  ...topicIds.map((id) => ({ id, label: topicCatalog[id].label, eyebrow: topicCatalog[id].eyebrow })),
];
